# Totale

##### setup

In [92]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import altair as alt
import os.path
import getpass
import platform
from pandasql import sqldf
import openpyxl

username = getpass.getuser()

print("Username: ", username)
pathPart1 = "/Users/"
pathPart2 = "/Github/SCGProject/Datasets/"
complePath = pathPart1+username+pathPart2

if platform.system() == "Darwin":
    if(username == "marcovinciguerra"):
        dfCambio = pd.read_csv(
            complePath+"/CorrectedDatasets/dfCambio.csv")

        dfClienti = pd.read_csv(
            complePath+"/CorrectedDatasets/dfClienti.csv")

        dfConsumi = pd.read_csv(
             complePath + "/CorrectedDatasets/dfConsumi.csv")

        dfCostoOrarioConsuntivo = pd.read_csv(
            complePath+"/CorrectedDatasets/dfConsuntivo.csv")

        dfCostoOrarioBudget = pd.read_csv(
            complePath+"CorrectedDatasets/dfCostoOrario.csv")

        dfImpiegoRisorse = pd.read_csv(
         complePath+"/CorrectedDatasets/dfImpiegoRisorse.csv")

        dftuttiClienti = pd.read_csv(
         complePath+"/CorrectedDatasets/dftuttiClienti.csv")

        dfVendite = pd.read_csv(
         complePath+"/CorrectedDatasets/dfVendite.csv")

    elif(username == "davidguzman"):
            pathPart1 = "/Users/"
            pathPart2 = "/documents/Github/SCGProject/Datasets/"
            complePath = pathPart1+username+pathPart2

            dfCambio = pd.read_csv(
                complePath+"/CorrectedDatasets/dfCambio.csv")

            dfClienti = pd.read_csv(
                complePath+"/CorrectedDatasets/dfClienti.csv")

            dfConsumi = pd.read_csv(
                complePath + "/CorrectedDatasets/dfConsumi.csv")

            dfCostoOrarioConsuntivo = pd.read_csv(
                complePath+"/CorrectedDatasets/dfConsuntivo.csv")

            dfCostoOrarioBudget = pd.read_csv(
                complePath+"CorrectedDatasets/dfCostoOrario.csv")

            dfImpiegoRisorse = pd.read_csv(
            complePath+"/CorrectedDatasets/dfImpiegoRisorse.csv")

            dftuttiClienti = pd.read_csv(
            complePath+"/CorrectedDatasets/dftuttiClienti.csv")

            dfVendite = pd.read_csv(
            complePath+"/CorrectedDatasets/dfVendite.csv")

elif platform.system() == "Linux":
    complePath = "/home/alinux/unibg/git_repo/SCGProject"
    pathPart1 = "/Users/"
    pathPart2 = "/documents/Github/SCGProject/Datasets/"
    complePath = pathPart1+username+pathPart2
    complePath = '/home/alinux/unibg/git_repo/SCGProject/Datasets/'

    dfCambio = pd.read_csv(
        complePath+"/CorrectedDatasets/dfCambio.csv")

    dfClienti = pd.read_csv(
        complePath+"/CorrectedDatasets/dfClienti.csv")

    dfConsumi = pd.read_csv(
        complePath + "/CorrectedDatasets/dfConsumi.csv")

    dfCostoOrarioConsuntivo = pd.read_csv(
        complePath+"/CorrectedDatasets/dfConsuntivo.csv")

    dfCostoOrarioBudget = pd.read_csv(
        complePath+"CorrectedDatasets/dfCostoOrario.csv")

    dfImpiegoRisorse = pd.read_csv(
        complePath+"/CorrectedDatasets/dfImpiegoRisorse.csv")

    dftuttiClienti = pd.read_csv(
        complePath+"/CorrectedDatasets/dftuttiClienti.csv")

    dfVendite = pd.read_csv(
        complePath+"/CorrectedDatasets/dfVendite.csv")



dfCambio["TassoCambioMedio"] = dfCambio["TassoCambioMedio"].str.replace(',','.')

Username:  davidguzman

# Ricavi

In [93]:
dfVendite.rename(columns = {'budget/cons':'budget'}, inplace = True)
venditeConsuntivo = sqldf("SELECT DISTINCT * FROM dfVendite WHERE budget = 'CONSUNTIVO' or budget = 'Consuntivo'")
venditeBudget = sqldf("SELECT DISTINCT * FROM dfVendite WHERE budget = 'BUDGET' or budget = 'Budget'")

In [94]:
print(venditeConsuntivo.shape, venditeBudget.shape)

(1767, 7) (1209, 7)

In [95]:
# join with dfCambio and dfClienti
venditeConsuntivo = sqldf('''SELECT DISTINCT v.NrMovimento, v.budget, v.NrArticolo, v.Quantity, v.ImportoVenditaValutaLocaleTOTALEVENDITA,k.TassoCambioMedio,v.ImportoVenditaValutaLocaleTOTALEVENDITA/k.TassoCambioMedio as TotaleEuro, v.NrOrigine, c.CodCondizioniPagam, c.FattCumulative, c.Valuta
FROM venditeConsuntivo as v join dfClienti as c on v.NrOrigine = c.Nr join dfCambio as k on c.Valuta = k.CodiceValuta
where k.Anno = 'Consuntivo' or k.Anno = 'CONSUNTIVO'
''')

venditeBudget = sqldf('''SELECT DISTINCT v.NrMovimento, v.budget, v.NrArticolo, v.Quantity, v.ImportoVenditaValutaLocaleTOTALEVENDITA,k.TassoCambioMedio,v.ImportoVenditaValutaLocaleTOTALEVENDITA/k.TassoCambioMedio as TotaleEuro, v.NrOrigine, c.CodCondizioniPagam, c.FattCumulative, c.Valuta
FROM venditeBudget as v join dfClienti as c on v.NrOrigine = c.Nr join dfCambio as k on c.Valuta = k.CodiceValuta
where k.Anno = 'Budget' or k.Anno = 'BUDGET'
''')

In [96]:
print(venditeConsuntivo.shape, venditeBudget.shape)

(1767, 11) (1209, 11)

In [97]:
sumVenditeConsuntivo = sqldf('select sum(TotaleEuro) as sumVenditaTotale from venditeConsuntivo')
sumVenditeBudget = sqldf('select sum(TotaleEuro) as sumVenditaTotale from venditeBudget')
print(sumVenditeConsuntivo)
print(sumVenditeBudget)
print(sumVenditeConsuntivo-sumVenditeBudget) #questo è lo scostamento totale dei ricavi

   sumVenditaTotale
0     507842.851413
   sumVenditaTotale
0     395335.892443
   sumVenditaTotale
0      112506.95897

# Costi

Materie prime

In [98]:
dfConsumi.rename(columns = {'Budget/cons':'budget'}, inplace = True)
consumiConsuntivo = sqldf("SELECT DISTINCT * FROM dfConsumi WHERE budget = 'CONSUNTIVO'")
consumiBudget = sqldf("SELECT DISTINCT * FROM dfConsumi WHERE budget = 'BUDGET'")
sumConsumiConsuntivo = sqldf('select sum(ImportoCostoTOTALE) from consumiConsuntivo')
sumConsumiBudget = sqldf('select sum(ImportoCostoTOTALE) from consumiBudget')
print(sumConsumiConsuntivo)
print(sumConsumiBudget)
print(sumConsumiConsuntivo-sumConsumiBudget) #questo è lo scostamento totale della materia prima

   sum(ImportoCostoTOTALE)
0                 289639.5
   sum(ImportoCostoTOTALE)
0                192906.47
   sum(ImportoCostoTOTALE)
0                 96733.03

Lavorazioni interne

In [99]:
impiegoConsuntivo = sqldf("SELECT DISTINCT * FROM dfImpiegoRisorse WHERE budgetConsuntivo = 'CONSUNTIVO' or budgetConsuntivo = 'Consuntivo'")
print(impiegoConsuntivo.shape)
#join con i costi orari
impiegoConsuntivo  = sqldf('''SELECT DISTINCT i.NrArticolo,i.budgetConsuntivo,i.NrOrdineProduzione,i.Descrizione,i.NrAreaProduzione,i.Risorsa,i.QuantitydiOutput,i.TempoRisorsa,c.CostoOrario
FROM impiegoConsuntivo as i join dfCostoOrarioConsuntivo as c 
on c.AreaProduzione = i.NrAreaProduzione and c.Risorsa = i.Risorsa''')
print(impiegoConsuntivo.shape)
# ci sono alcune quantità di output nulle, per gestire le sommiamo alle tuple con tutte le altre cose uguali
impiegoConsuntivoOld = sqldf('''select NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,sum(TempoRisorsa) as TempoRisorsa,CostoOrario, sum(QuantitydiOutput) as QuantitydiOutput
from impiegoConsuntivo
group by NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,CostoOrario
order by NrArticolo
''')
impiegoConsuntivo1 = impiegoConsuntivoOld.copy()
# ASSUNZIONE: la quantity di output maggiore tiene conto di tutte quelle inferiori.

(3791, 9)
(3723, 9)

In [100]:
impiegoConsuntivoNew = sqldf('''select NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,sum(TempoRisorsa) as TempoRisorsa,CostoOrario, max(QuantitydiOutput) as QuantitydiOutput
from impiegoConsuntivo
group by NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,CostoOrario
order by NrArticolo
''')
impiegoConsuntivoNew

,NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,TempoRisorsa,CostoOrario,QuantitydiOutput
0,ART0000018,CONSUNTIVO,ODP19-05998,Controllo qualità,CQ,RIS16,0.0000,15,2.0
1,ART0000018,CONSUNTIVO,ODP19-05998,Fresatura,A30,RIS5,1.0000,50,2.0
2,ART0000018,CONSUNTIVO,ODP19-05998,Tornitura,A20,RIS2,1.0000,80,2.0
3,ART0000041,CONSUNTIVO,ODP19-05998,Controllo qualità,CQ,RIS16,0.0000,15,4.0
4,ART0000041,CONSUNTIVO,ODP19-05998,Fresatura,A30,RIS1,0.0001,80,4.0
...,...,...,...,...,...,...,...,...,...
3012,ART0005136,CONSUNTIVO,ODP19-06532,Fresatura,A30,RIS14,1.2500,50,3.0
3013,ART0005136,CONSUNTIVO,ODP19-06533,Controllo qualità,CQ,RIS16,0.0000,15,4.0
3014,ART0005136,CONSUNTIVO,ODP19-06533,Tornitura,A20,RIS13,0.5000,80,4.0
3015,ART0005136,CONSUNTIVO,ODP19-06688,Controllo qualità,CQ,RIS16,0.0000,15,9.0
3016,ART0005136,CONSUNTIVO,ODP19-06688,Tornitura,A20,RIS2,1.0000,80,9.0

In [101]:
print(sqldf('select sum(QuantitydiOutput) from impiegoConsuntivoOld'))
print(sqldf('select sum(QuantitydiOutput) from impiegoConsuntivoNew'))

   sum(QuantitydiOutput)
0                25950.0
   sum(QuantitydiOutput)
0                25327.0

In [102]:
sqldf('select NrArticolo, NrOrdineProduzione, count(*) as c from impiegoConsuntivoNew group by NrArticolo, NrOrdineProduzione order by c')

      NrArticolo NrOrdineProduzione  c
0     ART0000116        ODP18-03472  1
1     ART0000116        ODP18-05889  1
2     ART0000119        ODP19-04430  1
3     ART0000121        ODP18-03469  1
4     ART0000128        ODP18-03529  1
...          ...                ... ..
1236  ART0005136        ODP19-01954  5
1237  ART0000043        ODP19-05998  6
1238  ART0001731        ODP18-04233  6
1239  ART0002360        ODP19-06224  6
1240  ART0004889        ODP18-06579  7

[1241 rows x 3 columns]

In [103]:
impiegoBudget = sqldf("SELECT DISTINCT * FROM dfImpiegoRisorse WHERE budgetConsuntivo = 'BUDGET' or budgetConsuntivo = 'Budget'")
#join con i costi orari
print(impiegoBudget.shape)
impiegoBudget = sqldf('''SELECT DISTINCT i.NrArticolo,i.budgetConsuntivo,i.NrOrdineProduzione,i.Descrizione,i.NrAreaProduzione,i.Risorsa,i.QuantitydiOutput,i.TempoRisorsa,c.CostoOrario
FROM impiegoBudget as i join dfCostoOrarioBudget as c 
on c.AreaProduzione = i.NrAreaProduzione and c.Risorsa = i.Risorsa''')
print(impiegoBudget.shape)
# righe a consuntivo sono di più che a budget e la somma dei 2 non corrisponde al numero di righe della tabella impiego risorse

# ci sono alcune quantità di output nulle, per gestire le sommiamo alle tuple con tutte le altre cose uguali
impiegoBudgetOld = sqldf('''select NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,sum(TempoRisorsa) as TempoRisorsa,CostoOrario, sum(QuantitydiOutput) as QuantitydiOutput
from impiegoBudget
group by NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,CostoOrario
order by NrArticolo
''')
impiegoBudget1 = impiegoBudgetOld.copy()

impiegoBudgetNew = sqldf('''select NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,sum(TempoRisorsa) as TempoRisorsa,CostoOrario, max(QuantitydiOutput) as QuantitydiOutput
from impiegoBudget
group by NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,CostoOrario
order by NrArticolo
''')

(2473, 9)
(2450, 9)

In [104]:
print(sqldf('select sum(QuantitydiOutput) from impiegoBudgetOld'))
print(sqldf('select sum(QuantitydiOutput) from impiegoBudgetNew'))

   sum(QuantitydiOutput)
0                15768.5
   sum(QuantitydiOutput)
0               15580.25

In [105]:
impiegoBudgetNew = sqldf('''select NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,sum(TempoRisorsa) as TempoRisorsa,CostoOrario, sum(QuantitydiOutput) as QuantitydiOutput
from impiegoBudgetNew
group by NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,CostoOrario
order by NrArticolo
''')

In [106]:
impiegoBudgetNew

sqldf('''select NrArticolo, NrOrdineProduzione, Descrizione, NrAreaProduzione, Risorsa, count(*)
from impiegoBudgetNew 
group by NrArticolo, NrOrdineProduzione, Descrizione, NrAreaProduzione, Risorsa
order by count(*) desc''')

sqldf('''select NrArticolo, Descrizione, NrAreaProduzione, Risorsa, count(*)
from impiegoBudgetNew 
group by NrArticolo, Descrizione, NrAreaProduzione, Risorsa
order by count(*) desc''')

      NrArticolo                Descrizione NrAreaProduzione Risorsa  count(*)
0     ART0005136          Controllo qualità               CQ   RIS16        19
1     ART0005136                  Tornitura              A20    RIS2        13
2     ART0000795          Controllo qualità               CQ   RIS16        11
3     ART0000762          Controllo qualità               CQ   RIS16         9
4     ART0000782          Controllo qualità               CQ   RIS16         8
...          ...                        ...              ...     ...       ...
1395  ART0005136  Brocciatura / stozzatrice              A33    RIS2         1
1396  ART0005136       Foratura/Maschiatura              A32    RIS9         1
1397  ART0005136                  Fresatura              A30    RIS1         1
1398  ART0005136                  Fresatura              A30   RIS13         1
1399  ART0005136            Taglio spezzoni              A20    RIS2         1

[1400 rows x 5 columns]

# Scostamento totale

In [107]:
sumImpiegoConsuntivo = sqldf(
    'SELECT sum(TempoRisorsa*CostoOrario) FROM impiegoConsuntivoNew WHERE TempoRisorsa>=0')
sumImpiegoBudget = sqldf(
    'SELECT sum(TempoRisorsa*CostoOrario) FROM impiegoBudgetNew WHERE TempoRisorsa>=0')
print(sumImpiegoConsuntivo)
print(sumImpiegoBudget)
print(sumImpiegoConsuntivo-sumImpiegoBudget)

   sum(TempoRisorsa*CostoOrario)
0                    359238.2962
   sum(TempoRisorsa*CostoOrario)
0                   194521.50346
   sum(TempoRisorsa*CostoOrario)
0                   164716.79274

In [108]:
print(sumVenditeConsuntivo.values[0][0])
print(sumImpiegoConsuntivo.values[0][0]+sumConsumiConsuntivo.values[0][0])
print(sumVenditeConsuntivo.values[0][0]-sumImpiegoConsuntivo.values[0][0]-sumConsumiConsuntivo.values[0][0])
print(sumVenditeBudget.values[0][0])
print(sumImpiegoBudget.values[0][0]+sumConsumiBudget.values[0][0])
print(sumVenditeBudget.values[0][0]-sumImpiegoBudget.values[0][0]-sumConsumiBudget.values[0][0])

507842.8514127266
648877.7962
-141034.94478727342
395335.8924431994
387427.97346000024
7907.918983199197

Senza vincoli su tempi negativi

**non cambia perché per ogni tempo negativo esiste un tempo positivo uguale in modulo che, al sommare i tempi delle stesse attività, si annullano a vicenda**

In [109]:
sumImpiegoConsuntivo = sqldf(
    'SELECT sum(TempoRisorsa*CostoOrario) FROM impiegoConsuntivoNew')
sumImpiegoBudget = sqldf(
    'SELECT sum(TempoRisorsa*CostoOrario) FROM impiegoBudgetNew')
print(sumImpiegoConsuntivo)
print(sumImpiegoBudget)
print(sumImpiegoConsuntivo-sumImpiegoBudget)

   sum(TempoRisorsa*CostoOrario)
0                    359215.7962
   sum(TempoRisorsa*CostoOrario)
0                   194521.50346
   sum(TempoRisorsa*CostoOrario)
0                   164694.29274

In [110]:
print(sumVenditeConsuntivo.values[0][0])
print(sumImpiegoConsuntivo.values[0][0]+sumConsumiConsuntivo.values[0][0])
print(sumVenditeConsuntivo.values[0][0]-sumImpiegoConsuntivo.values[0][0]-sumConsumiConsuntivo.values[0][0])
print(sumVenditeBudget.values[0][0])
print(sumImpiegoBudget.values[0][0]+sumConsumiBudget.values[0][0])
print(sumVenditeBudget.values[0][0]-sumImpiegoBudget.values[0][0]-sumConsumiBudget.values[0][0])

507842.8514127266
648855.2962
-141012.44478727342
395335.8924431994
387427.97346000024
7907.918983199197

# Socostamento di volume, impiego e prezzo per le Lavorazioni

#### consuntivo

In [111]:
# Creazione colonna ImpiegoUnitario
impiegoConsuntivoNew = sqldf(''' select NrArticolo, budgetConsuntivo, NrOrdineProduzione, Descrizione, NrAreaProduzione, Risorsa, TempoRisorsa, TempoRisorsa/QuantitydiOutput as ImpiegoUnitario, CostoOrario ,QuantitydiOutput
from impiegoConsuntivoNew''')
impiegoConsuntivoNew

,NrArticolo,budgetConsuntivo,NrOrdineProduzione,Descrizione,NrAreaProduzione,Risorsa,TempoRisorsa,ImpiegoUnitario,CostoOrario,QuantitydiOutput
0,ART0000018,CONSUNTIVO,ODP19-05998,Controllo qualità,CQ,RIS16,0.0000,0.000000,15,2.0
1,ART0000018,CONSUNTIVO,ODP19-05998,Fresatura,A30,RIS5,1.0000,0.500000,50,2.0
2,ART0000018,CONSUNTIVO,ODP19-05998,Tornitura,A20,RIS2,1.0000,0.500000,80,2.0
3,ART0000041,CONSUNTIVO,ODP19-05998,Controllo qualità,CQ,RIS16,0.0000,0.000000,15,4.0
4,ART0000041,CONSUNTIVO,ODP19-05998,Fresatura,A30,RIS1,0.0001,0.000025,80,4.0
...,...,...,...,...,...,...,...,...,...,...
3012,ART0005136,CONSUNTIVO,ODP19-06532,Fresatura,A30,RIS14,1.2500,0.416667,50,3.0
3013,ART0005136,CONSUNTIVO,ODP19-06533,Controllo qualità,CQ,RIS16,0.0000,0.000000,15,4.0
3014,ART0005136,CONSUNTIVO,ODP19-06533,Tornitura,A20,RIS13,0.5000,0.125000,80,4.0
3015,ART0005136,CONSUNTIVO,ODP19-06688,Controllo qualità,CQ,RIS16,0.0000,0.000000,15,9.0
3016,ART0005136,CONSUNTIVO,ODP19-06688,Tornitura,A20,RIS2,1.0000,0.111111,80,9.0

Avg out the null values

In [112]:
impiegoConsuntivoNew = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, sum(TempoRisorsa) as TempoRisorsa, avg(CostoOrario) as CostoOrario, max(QuantitydiOutput) as QuantitydiOutput
from impiegoConsuntivoNew
group by NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione
''')
impiegoConsuntivo = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, TempoRisorsa, (TempoRisorsa/QuantitydiOutput) as ImpiegoUnitario, CostoOrario,QuantitydiOutput
from impiegoConsuntivoNew
order by NrArticolo
''')

In [113]:
sqldf('select sum(TempoRisorsa*CostoOrario) from impiegoConsuntivo') # si mantiene quasi uguale!!

   sum(TempoRisorsa*CostoOrario)
0                  359425.545873

In [114]:
sqldf('select sum(ImpiegoUnitario*CostoOrario*QuantitydiOutput) from impiegoConsuntivo')

   sum(ImpiegoUnitario*CostoOrario*QuantitydiOutput)
0                                      358735.055873

la piccola differenza è dovuta alla restante parte di righe con output nulle e senza altre righe con output non nullo da sommare

In [115]:
sqldf('select * from impiegoConsuntivo where ImpiegoUnitario is null')

,NrArticolo,budgetConsuntivo,Descrizione,NrAreaProduzione,TempoRisorsa,ImpiegoUnitario,CostoOrario,QuantitydiOutput
0,ART0000151,CONSUNTIVO,Fresatura,A30,3.0000,None,50.0,0.0
1,ART0001789,CONSUNTIVO,Fresatura,A30,4.4990,None,50.0,0.0
2,ART0001872,CONSUNTIVO,Fresatura,A30,0.0001,None,80.0,0.0
3,ART0001873,CONSUNTIVO,Fresatura,A30,0.0001,None,80.0,0.0
4,ART0001939,CONSUNTIVO,Fresatura,A30,0.0001,None,80.0,0.0
5,ART0001942,CONSUNTIVO,Fresatura,A30,0.0001,None,80.0,0.0
6,ART0001945,CONSUNTIVO,Fresatura,A30,0.0001,None,80.0,0.0
7,ART0002152,CONSUNTIVO,Fresatura,A30,4.0000,None,50.0,0.0
8,ART0004146,CONSUNTIVO,Montaggio,A40,1.5000,None,50.0,0.0
9,ART0004357,CONSUNTIVO,Fresatura,A30,0.0100,None,50.0,0.0
10,ART0005136,CONSUNTIVO,None,A20,0.5000,None,80.0,0.0

#### ripetiamo per budget

In [116]:
impiegoBudgetNew = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, sum(TempoRisorsa) as TempoRisorsa, avg(CostoOrario) as CostoOrario, max(QuantitydiOutput) as QuantitydiOutput
from impiegoBudgetNew
group by NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione
''')
impiegoBudget = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, TempoRisorsa, (TempoRisorsa/QuantitydiOutput) as ImpiegoUnitario, CostoOrario,QuantitydiOutput
from impiegoBudgetNew
order by NrArticolo
''')

In [117]:
sqldf('select sum(TempoRisorsa*CostoOrario) from impiegoBudget') # si mantiene quasi uguale!!

   sum(TempoRisorsa*CostoOrario)
0                  194739.149842

In [118]:
sqldf('select sum(ImpiegoUnitario*CostoOrario*QuantitydiOutput) from impiegoBudget')

   sum(ImpiegoUnitario*CostoOrario*QuantitydiOutput)
0                                      192493.776242

In [119]:
sqldf('select * from impiegoBudget where ImpiegoUnitario is null')

,NrArticolo,budgetConsuntivo,Descrizione,NrAreaProduzione,TempoRisorsa,ImpiegoUnitario,CostoOrario,QuantitydiOutput
0,ART0000129,BUDGET,Fresatura,A30,0.0090,None,68.0,0.0
1,ART0000157,BUDGET,Tornitura,A20,15.0000,None,68.0,0.0
2,ART0000645,BUDGET,Fresatura,A30,1.0019,None,68.0,0.0
3,ART0000883,BUDGET,Fresatura,A30,1.0000,None,42.5,0.0
4,ART0001866,BUDGET,Rettifica,A34,10.0000,None,42.5,0.0
5,ART0001877,BUDGET,Fresatura,A30,0.0001,None,68.0,0.0
6,ART0001885,BUDGET,Fresatura,A30,0.0001,None,68.0,0.0
7,ART0001917,BUDGET,Fresatura,A30,0.0090,None,68.0,0.0
8,ART0003780,BUDGET,Fresatura,A30,1.5000,None,51.0,0.0
9,ART0004084,BUDGET,Montaggio,A40,3.1500,None,42.5,0.0
10,ART0004902,BUDGET,Fresatura,A30,0.0001,None,68.0,0.0
11,ART0005136,BUDGET,Foratura/Maschiatura,A32,3.0000,None,42.5,0.0
12,ART0005136,BUDGET,Montaggio,A40,8.2500,None,42.5,0.0

#### Merge/Join

In [120]:
impiegoConsuntivo.drop(['budgetConsuntivo'], axis=1, inplace=True)
impiegoBudget.drop(['budgetConsuntivo'], axis=1, inplace=True)
x = pd.merge(impiegoConsuntivo, impiegoBudget, on=['NrArticolo', 'Descrizione', 'NrAreaProduzione'], how='outer')
x

,NrArticolo,Descrizione,NrAreaProduzione,TempoRisorsa_x,ImpiegoUnitario_x,CostoOrario_x,QuantitydiOutput_x,TempoRisorsa_y,ImpiegoUnitario_y,CostoOrario_y,QuantitydiOutput_y
0,ART0000018,Controllo qualità,CQ,0.0000,0.000000,15.0,2.0,0.00,0.000000,12.75,2.0
1,ART0000018,Fresatura,A30,1.0000,0.500000,50.0,2.0,0.75,0.375000,51.00,2.0
2,ART0000018,Tornitura,A20,1.0000,0.500000,80.0,2.0,1.00,0.500000,68.00,2.0
3,ART0000041,Controllo qualità,CQ,0.0000,0.000000,15.0,4.0,0.00,0.000000,12.75,4.0
4,ART0000041,Fresatura,A30,0.0001,0.000025,80.0,4.0,1.25,0.312500,51.00,4.0
...,...,...,...,...,...,...,...,...,...,...,...
1345,ART0004904,Tornitura,A20,NaN,NaN,NaN,NaN,1.75,0.437500,68.00,4.0
1346,ART0004944,Tornitura,A20,NaN,NaN,NaN,NaN,1.75,0.218750,68.00,8.0
1347,ART0005091,Fresatura,A30,NaN,NaN,NaN,NaN,1.00,0.250000,42.50,4.0
1348,ART0005136,Foratura/Maschiatura,A32,NaN,NaN,NaN,NaN,3.00,NaN,42.50,0.0
1349,ART0005136,Taglio spezzoni,A20,NaN,NaN,NaN,NaN,4.50,0.155172,68.00,29.0

In [121]:
c = sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x) from x').iloc[0][0]
b = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_y) from x').iloc[0][0]
print(c)
print(b)
print(c-b)
# non altera i totali!!

358735.05587289936
192493.7762416667
166241.27963123267

In [122]:
#Budget Standard
BudgetStandardLav = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_y) from x').iloc[0][0]
# Impiego Standard (volume a consuntivo)
ImpiegoStandardLav = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_x) from x').iloc[0][0]
# Impiego Effettivo (volume e impiego a consuntivo)
ImpiegoEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_y*QuantitydiOutput_x) from x').iloc[0][0]
# Budget Effettivo (tutto a consuntivo)
BudgetEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x) from x').iloc[0][0]
print(BudgetStandardLav)
print(ImpiegoStandardLav)
print(ImpiegoEffettivoLav)
print(BudgetEffettivoLav)

192493.7762416667
250080.51605938777
281289.91565333324
358735.05587289936

In [123]:
sqldf('select ImpiegoUnitario_y,CostoOrario_y,QuantitydiOutput_x from x order by QuantitydiOutput_x desc')

      ImpiegoUnitario_y  CostoOrario_y  QuantitydiOutput_x
0              0.000000      12.750000               116.0
1              0.020455      68.000000               116.0
2              0.000000      12.750000               115.0
3              1.047170      63.750000               115.0
4              0.129167      53.833333               110.0
...                 ...            ...                 ...
1345           0.437500      68.000000                 NaN
1346           0.218750      68.000000                 NaN
1347           0.250000      42.500000                 NaN
1348                NaN      42.500000                 NaN
1349           0.155172      68.000000                 NaN

[1350 rows x 3 columns]

In [124]:
#Scostamenti
ScostamentoVolumeLav = ImpiegoStandardLav-b
ScostamentoImpiegoLav = ImpiegoEffettivoLav-ImpiegoStandardLav
ScostamentoPrezzoLav = BudgetEffettivoLav-ImpiegoEffettivoLav
print(ScostamentoVolumeLav)
print(ScostamentoImpiegoLav)
print(ScostamentoPrezzoLav)
print(ScostamentoVolumeLav+ScostamentoImpiegoLav+ScostamentoPrezzoLav)

57586.73981772107
31209.399593945476
77445.14021956612
166241.27963123267

# Socostamento di volume, impiego e prezzo per le materie prime

#### Group by CodiceMP

se non facciamo qualche group by a priori si sdoppiano le righe, proviamo prima con CodiceMP

In [125]:
consumiConsuntivoUnitByMP = sqldf('''select CodiceMP, NrArticolo, NrDocumento as NrOrdineProduzione, sum(QuantityMPImpiegata) as QuantityMPImpiegata, sum(ImportoCostoTOTALE) as ImportoCostoTOTALE
from consumiConsuntivo     
group by CodiceMP, NrArticolo, NrOrdineProduzione''')
consumiBudgetUnitByMP = sqldf('''select CodiceMP, NrArticolo,NrDocumento as NrOrdineProduzione, sum(QuantityMPImpiegata) as QuantityMPImpiegata, sum(ImportoCostoTOTALE) as ImportoCostoTOTALE
from consumiBudget     
group by CodiceMP, NrArticolo,NrOrdineProduzione''')
consumiConsuntivoUnitByMP

,CodiceMP,NrArticolo,NrOrdineProduzione,QuantityMPImpiegata,ImportoCostoTOTALE
0,ART0000771,ART0005136,ODP19-01043,1.0,230.95
1,ART0000809,ART0005136,ODP19-01043,2.0,1122.70
2,ART0001066,ART0003099,ODP18-08457,1064.0,1.99
3,ART0001068,ART0004671,ODP19-04541,190.0,6.84
4,ART0001073,ART0002240,ODP18-06051,184.0,15.95
...,...,...,...,...,...
2766,ART0007130,ART0001228,ODP19-06232,15.0,22.50
2767,ART0007133,ART0005136,ODP19-06532,3.0,0.00
2768,ART0007141,ART0002191,ODP19-06418,2.0,13.00
2769,ART0007148,ART0002619,ODP19-05754,2.0,60.00
2770,ART0007166,ART0000877,ODP19-06659,3.0,107.45

##### ritrovare volumi di produzione

In [126]:
temp = sqldf('''select a.CodiceMP,a.NrArticolo,a.NrOrdineProduzione,a.QuantityMPImpiegata,a.ImportoCostoTOTALE,
 (select max(QuantitydiOutput) from impiegoConsuntivoNew  where a.NrArticolo = NrArticolo and a.NrOrdineProduzione = NrOrdineProduzione) as QuantitydiOutput
 from consumiConsuntivoUnitByMP as a''')
temp = sqldf('''select distinct CodiceMP,NrArticolo,sum(QuantityMPImpiegata) as QuantityMPImpiegata,sum(ImportoCostoTOTALE) as ImportoCostoTOTALE ,QuantitydiOutput 
from temp group by CodiceMP,NrArticolo''')
temp

,CodiceMP,NrArticolo,QuantityMPImpiegata,ImportoCostoTOTALE,QuantitydiOutput
0,ART0000771,ART0005136,1.0,230.95,102.0
1,ART0000809,ART0005136,2.0,1122.70,102.0
2,ART0001066,ART0003099,1064.0,1.99,19.0
3,ART0001068,ART0004671,190.0,6.84,5.0
4,ART0001073,ART0002240,184.0,15.95,4.0
...,...,...,...,...,...
1074,ART0007130,ART0001228,15.0,22.50,15.0
1075,ART0007133,ART0005136,3.0,0.00,102.0
1076,ART0007141,ART0002191,2.0,13.00,2.0
1077,ART0007148,ART0002619,2.0,60.00,2.0
1078,ART0007166,ART0000877,3.0,107.45,3.0

In [127]:
temp = sqldf('''select a.CodiceMP,a.NrArticolo,a.NrOrdineProduzione,a.QuantityMPImpiegata,a.ImportoCostoTOTALE,
 (select max(QuantitydiOutput) from impiegoConsuntivoNew  where a.NrArticolo = NrArticolo and a.NrOrdineProduzione = NrOrdineProduzione) as QuantitydiOutput
 from consumiConsuntivoUnitByMP as a''')
temp = sqldf('''select distinct CodiceMP,NrArticolo,sum(QuantityMPImpiegata) as QuantityMPImpiegata,sum(ImportoCostoTOTALE) as ImportoCostoTOTALE ,QuantitydiOutput 
from temp group by CodiceMP,NrArticolo''')
consumiConsuntivoVolProd = sqldf('''select distinct CodiceMP,NrArticolo,QuantityMPImpiegata/QuantitydiOutput as ImpiegoPerPezzo,ImportoCostoTOTALE/QuantityMPImpiegata as CostoPerUnitaMis,QuantitydiOutput, ImportoCostoTOTALE
from temp group by CodiceMP,NrArticolo''')

temp = sqldf('''select a.CodiceMP,a.NrArticolo,a.NrOrdineProduzione,a.QuantityMPImpiegata,a.ImportoCostoTOTALE,
 (select max(QuantitydiOutput) from impiegoBudgetNew  where a.NrArticolo = NrArticolo and a.NrOrdineProduzione = NrOrdineProduzione) as QuantitydiOutput
 from consumiBudgetUnitByMP as a''')
temp = sqldf('''select distinct CodiceMP,NrArticolo,sum(QuantityMPImpiegata) as QuantityMPImpiegata,sum(ImportoCostoTOTALE) as ImportoCostoTOTALE ,QuantitydiOutput 
from temp group by CodiceMP,NrArticolo''')
consumiBudgetVolProd  = sqldf('''select distinct CodiceMP,NrArticolo,QuantityMPImpiegata/QuantitydiOutput as ImpiegoPerPezzo,ImportoCostoTOTALE/QuantityMPImpiegata as CostoPerUnitaMis,QuantitydiOutput, ImportoCostoTOTALE
from temp group by CodiceMP,NrArticolo''')

consumiConsuntivoVolProd

,CodiceMP,NrArticolo,ImpiegoPerPezzo,CostoPerUnitaMis,QuantitydiOutput,ImportoCostoTOTALE
0,ART0000771,ART0005136,0.009804,230.950000,102.0,230.95
1,ART0000809,ART0005136,0.019608,561.350000,102.0,1122.70
2,ART0001066,ART0003099,56.000000,0.001870,19.0,1.99
3,ART0001068,ART0004671,38.000000,0.036000,5.0,6.84
4,ART0001073,ART0002240,46.000000,0.086685,4.0,15.95
...,...,...,...,...,...,...
1074,ART0007130,ART0001228,1.000000,1.500000,15.0,22.50
1075,ART0007133,ART0005136,0.029412,0.000000,102.0,0.00
1076,ART0007141,ART0002191,1.000000,6.500000,2.0,13.00
1077,ART0007148,ART0002619,1.000000,30.000000,2.0,60.00
1078,ART0007166,ART0000877,1.000000,35.816667,3.0,107.45

In [128]:
print(consumiConsuntivoVolProd.shape, consumiConsuntivoUnitByMP.shape)
print(consumiBudgetVolProd.shape, consumiBudgetVolProd.shape)

(1079, 6) (2771, 5)
(937, 6) (937, 6)

In [129]:
print(sqldf('select * from consumiConsuntivoVolProd where CostoPerUnitaMis is null').shape)
print(sqldf('select * from consumiBudgetVolProd where CostoPerUnitaMis is null').shape)
# TODO rimuovere la maggior parte di quanitity nulle possibile dalle lavorazioni continua a essere importante!

(0, 6)
(0, 6)

In [130]:
print(sqldf('select sum(ImportoCostoTOTALE) from consumiConsuntivoUnitByMP'))
print(sqldf('select sum(ImpiegoPerPezzo*CostoPerUnitaMis*QuantitydiOutput) from consumiConsuntivoVolProd'))
print(sqldf('select sum(ImportoCostoTOTALE) from consumiBudgetUnitByMP'))
print(sqldf('select sum(ImpiegoPerPezzo*CostoPerUnitaMis*QuantitydiOutput) from consumiBudgetVolProd'))
# non si perdono dei decimali

   sum(ImportoCostoTOTALE)
0                 289639.5
   sum(ImpiegoPerPezzo*CostoPerUnitaMis*QuantitydiOutput)
0                                          289033.53
   sum(ImportoCostoTOTALE)
0                192906.47
   sum(ImpiegoPerPezzo*CostoPerUnitaMis*QuantitydiOutput)
0                                          192204.42

##### Scostamenti

In [131]:
#consumiConsuntivoVolProd.drop(columns='NrOrdineProduzione',inplace=True)
#consumiBudgetVolProd.drop(columns='NrOrdineProduzione',inplace=True)

In [132]:
ConsumiUnit = pd.merge(consumiConsuntivoVolProd,consumiBudgetVolProd, on = ['CodiceMP','NrArticolo'], how = 'outer')
ConsumiUnit

,CodiceMP,NrArticolo,ImpiegoPerPezzo_x,CostoPerUnitaMis_x,QuantitydiOutput_x,ImportoCostoTOTALE_x,ImpiegoPerPezzo_y,CostoPerUnitaMis_y,QuantitydiOutput_y,ImportoCostoTOTALE_y
0,ART0000771,ART0005136,0.009804,230.950000,102.0,230.95,NaN,NaN,NaN,NaN
1,ART0000809,ART0005136,0.019608,561.350000,102.0,1122.70,NaN,NaN,NaN,NaN
2,ART0001066,ART0003099,56.000000,0.001870,19.0,1.99,NaN,NaN,NaN,NaN
3,ART0001068,ART0004671,38.000000,0.036000,5.0,6.84,NaN,NaN,NaN,NaN
4,ART0001073,ART0002240,46.000000,0.086685,4.0,15.95,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1310,ART0005913,ART0002191,NaN,NaN,NaN,NaN,20.0,0.339250,2.0,13.57
1311,ART0005917,ART0001610,NaN,NaN,NaN,NaN,243.0,0.000597,4.0,0.58
1312,ART0005930,ART0000229,NaN,NaN,NaN,NaN,130.0,0.005064,12.0,7.90
1313,ART0005935,ART0004675,NaN,NaN,NaN,NaN,45.0,0.014311,5.0,3.22
1314,ART0005943,ART0001731,NaN,NaN,NaN,NaN,2.0,4.500000,10.0,90.00

In [133]:
BudgetEffettivoMP = sqldf('select sum(QuantitydiOutput_x*ImpiegoPerPezzo_x*CostoPerUnitaMis_x) from ConsumiUnit').iloc[0][0]
ImpiegoEffettivoMP = sqldf('select sum(QuantitydiOutput_x*ImpiegoPerPezzo_x*CostoPerUnitaMis_y) from ConsumiUnit').iloc[0][0]
ImpiegoStandardMP = sqldf('select sum(QuantitydiOutput_x*ImpiegoPerPezzo_y*CostoPerUnitaMis_y) from ConsumiUnit').iloc[0][0]
BudgetStandardMP = sqldf('select sum(QuantitydiOutput_y*ImpiegoPerPezzo_y*CostoPerUnitaMis_y) from ConsumiUnit').iloc[0][0]
ScostamentoVolumeMP =  ImpiegoStandardMP - BudgetStandardMP
ScostamentoImpiegoMP = ImpiegoEffettivoMP-ImpiegoStandardMP
ScostamentoPrezzoMP = BudgetEffettivoMP-ImpiegoEffettivoMP

In [134]:
print(BudgetEffettivoMP)
print(ImpiegoEffettivoMP)
print(ImpiegoStandardMP)
print(BudgetStandardMP)
print(ScostamentoVolumeMP)
print(ScostamentoImpiegoMP)
print(ScostamentoPrezzoMP)
print(ScostamentoVolumeMP+ScostamentoImpiegoMP+ScostamentoPrezzoMP)

289033.53000000014
272523.2279339363
189145.68359840667
192204.42
-3058.7364015933417
83377.54433552962
16510.302066063858
96829.11000000013

# Socostamento di volume, mix e prezzo per i ricavi

 group by NrArticolo dei ricavi

In [135]:
venditeConsuntivoArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity, sum(TotaleEuro) as TotaleEuro
        from venditeConsuntivo
        group by NrArticolo''')
venditeConsuntivoArt

     NrArticolo  Quantity    TotaleEuro
0    ART0000018         2     91.720170
1    ART0000041         4    400.233470
2    ART0000042         4    600.350204
3    ART0000043         2    250.145918
4    ART0000115         3   1095.000000
..          ...       ...           ...
408  ART0005109         9    210.122572
409  ART0005110         9    435.253898
410  ART0005111         7    204.285833
411  ART0005112         7    262.653214
412  ART0005136      1676  10502.137768

[413 rows x 3 columns]

In [136]:
venditeBudgetArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity, sum(TotaleEuro) as TotaleEuro
        from venditeBudget
        group by NrArticolo''')
venditeBudgetArt

     NrArticolo  Quantity    TotaleEuro
0    ART0000018         2     85.380894
1    ART0000041         4    360.497107
2    ART0000042         4    569.205958
3    ART0000043         2    218.195617
4    ART0000115        12   1965.000000
..          ...       ...           ...
408  ART0005109         4    106.251779
409  ART0005110         2     94.867660
410  ART0005111         2     66.407362
411  ART0005112         2     85.380894
412  ART0005136       630  12932.919149

[413 rows x 3 columns]

##### calcolo del delta dei volumi

In [137]:

vendite = pd.merge(venditeConsuntivoArt,venditeBudgetArt, on = ['NrArticolo'], how = 'outer')
vendite

     NrArticolo  Quantity_x  TotaleEuro_x  Quantity_y  TotaleEuro_y
0    ART0000018           2     91.720170           2     85.380894
1    ART0000041           4    400.233470           4    360.497107
2    ART0000042           4    600.350204           4    569.205958
3    ART0000043           2    250.145918           2    218.195617
4    ART0000115           3   1095.000000          12   1965.000000
..          ...         ...           ...         ...           ...
408  ART0005109           9    210.122572           4    106.251779
409  ART0005110           9    435.253898           2     94.867660
410  ART0005111           7    204.285833           2     66.407362
411  ART0005112           7    262.653214           2     85.380894
412  ART0005136        1676  10502.137768         630  12932.919149

[413 rows x 5 columns]

In [138]:
sqldf('''select sum(TotaleEuro_x) from vendite''')

   sum(TotaleEuro_x)
0      507842.851413

In [139]:
sqldf('''select sum(TotaleEuro_y) from vendite''')

   sum(TotaleEuro_y)
0      395335.892443

In [140]:
sqldf('''select NrArticolo, Quantity_x-Quantity_y as DiffQuantity
        from vendite
        order by DiffQuantity desc
        ''')

     NrArticolo  DiffQuantity
0    ART0005136          1046
1    ART0000748           291
2    ART0001575           200
3    ART0004397           114
4    ART0000229           113
..          ...           ...
408  ART0001628           -96
409  ART0004363          -114
410  ART0001154          -176
411  ART0003610          -176
412  ART0003780          -320

[413 rows x 2 columns]

In [141]:
sqldf('''select sum(Quantity_x-Quantity_y) as DiffQuantity
        from vendite
        ''')

   DiffQuantity
0          2105

##### creazione colonne mix, volume, prezzo unitario

In [142]:
venditeBudgetS = sqldf('''select NrArticolo, (Quantity*100000000000/7224) as Mix, 7224 as VolumeTotale, TotaleEuro/Quantity as PrezzoUnitario
        from venditeBudgetArt''')
venditeBudgetS

     NrArticolo         Mix  VolumeTotale  PrezzoUnitario
0    ART0000018    27685492          7224       42.690447
1    ART0000041    55370985          7224       90.124277
2    ART0000042    55370985          7224      142.301489
3    ART0000043    27685492          7224      109.097809
4    ART0000115   166112956          7224      163.750000
..          ...         ...           ...             ...
408  ART0005109    55370985          7224       26.562945
409  ART0005110    27685492          7224       47.433830
410  ART0005111    27685492          7224       33.203681
411  ART0005112    27685492          7224       42.690447
412  ART0005136  8720930232          7224       20.528443

[413 rows x 4 columns]

In [143]:
sqldf('select sum(Mix*VolumeTotale*PrezzoUnitario)/100000000000 from venditeBudgetS')

   sum(Mix*VolumeTotale*PrezzoUnitario)/100000000000
0                                      395335.890784

In [144]:
sqldf('select sum(Quantity) from venditeConsuntivo')

   sum(Quantity)
0           9329

In [145]:
venditeConsuntivoS = sqldf('''select NrArticolo, (Quantity*100000000000/9329) as Mix, 9329 as VolumeTotale, TotaleEuro/Quantity as PrezzoUnitario
        from venditeConsuntivoArt''')
venditeConsuntivoS

     NrArticolo          Mix  VolumeTotale  PrezzoUnitario
0    ART0000018     21438525          9329       45.860085
1    ART0000041     42877050          9329      100.058367
2    ART0000042     42877050          9329      150.087551
3    ART0000043     21438525          9329      125.072959
4    ART0000115     32157787          9329      365.000000
..          ...          ...           ...             ...
408  ART0005109     96473362          9329       23.346952
409  ART0005110     96473362          9329       48.361544
410  ART0005111     75034837          9329       29.183690
411  ART0005112     75034837          9329       37.521888
412  ART0005136  17965483974          9329        6.266192

[413 rows x 4 columns]

In [146]:
sqldf('select sum(Mix*VolumeTotale*PrezzoUnitario)/100000000000 from venditeConsuntivoS')

   sum(Mix*VolumeTotale*PrezzoUnitario)/100000000000
0                                      507842.849547

### Calcolo socostamenti di volume, mix e prezzo

In [147]:
venditeS = pd.merge(venditeConsuntivoS, venditeBudgetS, on = ['NrArticolo'], how = 'outer')
venditeS

,NrArticolo,Mix_x,VolumeTotale_x,PrezzoUnitario_x,Mix_y,VolumeTotale_y,PrezzoUnitario_y
0,ART0000018,21438525,9329,45.860085,27685492,7224,42.690447
1,ART0000041,42877050,9329,100.058367,55370985,7224,90.124277
2,ART0000042,42877050,9329,150.087551,55370985,7224,142.301489
3,ART0000043,21438525,9329,125.072959,27685492,7224,109.097809
4,ART0000115,32157787,9329,365.000000,166112956,7224,163.750000
...,...,...,...,...,...,...,...
408,ART0005109,96473362,9329,23.346952,55370985,7224,26.562945
409,ART0005110,96473362,9329,48.361544,27685492,7224,47.433830
410,ART0005111,75034837,9329,29.183690,27685492,7224,33.203681
411,ART0005112,75034837,9329,37.521888,27685492,7224,42.690447
412,ART0005136,17965483974,9329,6.266192,8720930232,7224,20.528443

In [148]:
sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x)/100000000000 from venditeS')

   sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x)/100000000000
0                                      507842.849547

In [149]:
z = sqldf('select NrArticolo,(Mix_y*VolumeTotale_y*PrezzoUnitario_y)/100000000000 as c from venditeS ')
z

     NrArticolo             c
0    ART0000018     85.380891
1    ART0000041    360.497103
2    ART0000042    569.205951
3    ART0000043    218.195611
4    ART0000115   1964.999990
..          ...           ...
408  ART0005109    106.251778
409  ART0005110     94.867657
410  ART0005111     66.407360
411  ART0005112     85.380891
412  ART0005136  12932.919148

[413 rows x 2 columns]

In [150]:
BudgetStandardRic = sqldf('select sum(Mix_y*VolumeTotale_y*PrezzoUnitario_y)/100000000000 from venditeS ').iloc[0][0]
MixStandardRic = sqldf('select sum(Mix_y*VolumeTotale_x*PrezzoUnitario_y)/100000000000 from venditeS ').iloc[0][0]
MixEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_y)/100000000000 from venditeS ').iloc[0][0]
BudgetEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x)/100000000000 from venditeS ').iloc[0][0]

In [151]:
print(BudgetStandardRic)
print(MixStandardRic)
print(MixEffettivoRic)
print(BudgetEffettivoRic)

395335.8907839928
510532.7415730725
539112.4259562771
507842.84954721347

In [152]:
ScostamentoVolumeRic = MixStandardRic-BudgetStandardRic
ScostamentoMixRic = MixEffettivoRic-MixStandardRic
ScostamentoPrezzoRic = BudgetEffettivoRic-MixEffettivoRic

In [153]:
print(ScostamentoVolumeRic)
print(ScostamentoMixRic)
print(ScostamentoPrezzoRic)
print(ScostamentoVolumeRic+ScostamentoMixRic+ScostamentoPrezzoRic)

115196.85078907968
28579.684383204556
-31269.576409063593
112506.95876322064

# Vista globale degli scostamenti

In [154]:
data = {'Index': ['Ricavi', 'CostiMP', 'CostiLav', 'Margine'], 
        'Budget' : [BudgetStandardRic, BudgetStandardMP,BudgetStandardLav, (BudgetStandardRic - (BudgetStandardMP+BudgetStandardLav))],
        'ScostamentoVolume' : [ScostamentoVolumeRic,ScostamentoVolumeMP,ScostamentoVolumeLav, (ScostamentoVolumeRic - (ScostamentoVolumeMP+ScostamentoVolumeLav))], 
        'MixStandard' : [MixStandardRic, ImpiegoStandardMP,ImpiegoStandardLav, (MixStandardRic - (ImpiegoStandardMP+ImpiegoStandardLav))],
        'ScostamentoMix' : [ScostamentoMixRic,ScostamentoImpiegoMP,ScostamentoImpiegoLav, (ScostamentoMixRic - (ScostamentoImpiegoMP+ScostamentoImpiegoLav))],
        'MixEffettivo' : [MixEffettivoRic, ImpiegoEffettivoMP,ImpiegoEffettivoLav, (MixEffettivoRic - (ImpiegoEffettivoMP+ImpiegoEffettivoLav))],
        'ScostamentoPrezzo' : [ScostamentoPrezzoRic,ScostamentoPrezzoMP,ScostamentoPrezzoLav, (ScostamentoPrezzoRic - (ScostamentoPrezzoMP+ScostamentoPrezzoLav))], 
        'Consuntivo' : [BudgetEffettivoRic, BudgetEffettivoMP, BudgetEffettivoLav, (BudgetEffettivoRic - (BudgetEffettivoMP+BudgetEffettivoLav))],
        'ScostamentoTotale' : [BudgetEffettivoRic-BudgetStandardRic,BudgetEffettivoMP-BudgetStandardMP,BudgetEffettivoLav-BudgetStandardLav, (BudgetEffettivoRic - BudgetStandardRic - (BudgetEffettivoMP-BudgetStandardMP+BudgetEffettivoLav-BudgetStandardLav))]}

In [155]:
pd.DataFrame(data)

,Index,Budget,ScostamentoVolume,MixStandard,ScostamentoMix,MixEffettivo,ScostamentoPrezzo,Consuntivo,ScostamentoTotale
0,Ricavi,395335.890784,115196.850789,510532.741573,28579.684383,539112.425956,-31269.576409,507842.849547,112506.958763
1,CostiMP,192204.420000,-3058.736402,189145.683598,83377.544336,272523.227934,16510.302066,289033.530000,96829.110000
2,CostiLav,192493.776242,57586.739818,250080.516059,31209.399594,281289.915653,77445.140220,358735.055873,166241.279631
3,Margine,10637.694542,60668.847373,71306.541915,-86007.259546,-14700.717631,-125225.018695,-139925.736326,-150563.430868

In [156]:
print(-119959.519152+96308.420839-125320.243955)

-148971.342268

# Repeat ma tenendo conto della valuta

In [157]:
venditeConsuntivoArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity,  sum(ImportoVenditaValutaLocaleTOTALEVENDITA) as TotaleLocale, Valuta, TassoCambioMedio
        from venditeConsuntivo
        group by NrArticolo, Valuta, TassoCambioMedio''')
venditeBudgetArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity, sum(ImportoVenditaValutaLocaleTOTALEVENDITA) as TotaleLocale, Valuta, TassoCambioMedio
        from venditeBudget
        group by NrArticolo, Valuta, TassoCambioMedio ''')

In [158]:
venditeBudgetArt

     NrArticolo  Quantity  TotaleLocale  Valuta TassoCambioMedio
0    ART0000018         2         90.00       2           1.0541
1    ART0000041         4        380.00       2           1.0541
2    ART0000042         4        600.00       2           1.0541
3    ART0000043         2        230.00       2           1.0541
4    ART0000115        12       1965.00       1                1
..          ...       ...           ...     ...              ...
410  ART0005111         2         70.00       2           1.0541
411  ART0005112         2         90.00       2           1.0541
412  ART0005136        87       8933.00       1                1
413  ART0005136        80       4175.21       2           1.0541
414  ART0005136       463       4812.00       3            123.4

[415 rows x 5 columns]

##### creazione colonne mix, volume, prezzo unitario (locale)

In [159]:
venditeConsuntivoS = sqldf('''select NrArticolo, (Quantity*100000000000/9329) as Mix, 9329 as VolumeTotale, TotaleLocale/Quantity as PrezzoUnitario, Valuta, TassoCambioMedio, (TotaleLocale/Quantity)/TassoCambioMedio as PrezzoUnitarioEuro
        from venditeConsuntivoArt''')
venditeBudgetS = sqldf('''select NrArticolo, (Quantity*100000000000/7224) as Mix, 7224 as VolumeTotale, TotaleLocale/Quantity as PrezzoUnitario, Valuta, TassoCambioMedio, (TotaleLocale/Quantity)/TassoCambioMedio as PrezzoUnitarioEuro
        from venditeBudgetArt''')

### Calcolo socostamenti di volume, mix, prezzo e valuta

In [160]:
venditeS1 = pd.merge(venditeConsuntivoS, venditeBudgetS, on = ['NrArticolo', 'Valuta'], how = 'outer')
venditeS1
#venditeS1.to_excel('venditeS1.xlsx')

,NrArticolo,Mix_x,VolumeTotale_x,PrezzoUnitario_x,Valuta,TassoCambioMedio_x,PrezzoUnitarioEuro_x,Mix_y,VolumeTotale_y,PrezzoUnitario_y,TassoCambioMedio_y,PrezzoUnitarioEuro_y
0,ART0000018,21438525,9329,55.000000,2,1.1993,45.860085,27685492,7224,45.000000,1.0541,42.690447
1,ART0000041,42877050,9329,120.000000,2,1.1993,100.058367,55370985,7224,95.000000,1.0541,90.124277
2,ART0000042,42877050,9329,180.000000,2,1.1993,150.087551,55370985,7224,150.000000,1.0541,142.301489
3,ART0000043,21438525,9329,150.000000,2,1.1993,125.072959,27685492,7224,115.000000,1.0541,109.097809
4,ART0000115,32157787,9329,365.000000,1,1,365.000000,166112956,7224,163.750000,1,163.750000
...,...,...,...,...,...,...,...,...,...,...,...,...
410,ART0005111,75034837,9329,35.000000,2,1.1993,29.183690,27685492,7224,35.000000,1.0541,33.203681
411,ART0005112,75034837,9329,45.000000,2,1.1993,37.521888,27685492,7224,45.000000,1.0541,42.690447
412,ART0005136,686032800,9329,39.109375,1,1,39.109375,1204318936,7224,102.678161,1,102.678161
413,ART0005136,439489763,9329,229.121951,2,1.1993,191.046403,1107419712,7224,52.190125,1.0541,49.511550
414,ART0005136,16839961410,9329,14.286073,3,135.01,0.105815,6409191583,7224,10.393089,123.4,0.084223

In [161]:
BudgetStandardRic = sqldf('select sum(Mix_y*VolumeTotale_y*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
MixStandardRic = sqldf('select sum(Mix_y*VolumeTotale_x*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
MixEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
BudgetEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
BudgetEffettivoValutaRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x/TassoCambioMedio_x)/100000000000 from venditeS1 ').iloc[0][0]

In [162]:
print(BudgetStandardRic)
print(MixStandardRic)
print(MixEffettivoRic)
print(BudgetEffettivoRic)
print(BudgetEffettivoValutaRic)

395335.8907780576
510532.74156540784
513440.445133813
569389.7443994995
507842.8495423171

In [163]:
ScostamentoVolumeRic = MixStandardRic-BudgetStandardRic
ScostamentoMixRic = MixEffettivoRic-MixStandardRic
ScostamentoPrezzoRic = BudgetEffettivoRic-MixEffettivoRic
ScostamentoValutaRic = BudgetEffettivoValutaRic-BudgetEffettivoRic

In [164]:
print(ScostamentoVolumeRic)
print(ScostamentoMixRic)
print(ScostamentoPrezzoRic)
print(ScostamentoValutaRic)
print(ScostamentoVolumeRic+ScostamentoMixRic+ScostamentoPrezzoRic+ScostamentoValutaRic)

115196.85078735021
2907.7035684051807
55949.29926568648
-61546.8948571824
112506.95876425947

# Vista globale degli scostamenti v2

In [165]:
data = {'Index': ['Ricavi', 'CostiMP', 'CostiLav', 'Margine'], 
        'Budget' : [BudgetStandardRic, BudgetStandardMP,BudgetStandardLav, (BudgetStandardRic - (BudgetStandardMP+BudgetStandardLav))],
        'ScostamentoVolume' : [ScostamentoVolumeRic,ScostamentoVolumeMP,ScostamentoVolumeLav, (ScostamentoVolumeRic - (ScostamentoVolumeMP+ScostamentoVolumeLav))], 
        'MixStandard' : [MixStandardRic, ImpiegoStandardMP,ImpiegoStandardLav, (MixStandardRic - (ImpiegoStandardMP+ImpiegoStandardLav))],
        'ScostamentoMix' : [ScostamentoMixRic,ScostamentoImpiegoMP,ScostamentoImpiegoLav, (ScostamentoMixRic - (ScostamentoImpiegoMP+ScostamentoImpiegoLav))],
        'MixEffettivo' : [MixEffettivoRic, ImpiegoEffettivoMP,ImpiegoEffettivoLav, (MixEffettivoRic - (ImpiegoEffettivoMP+ImpiegoEffettivoLav))],
        'ScostamentoPrezzo' : [ScostamentoPrezzoRic,ScostamentoPrezzoMP,ScostamentoPrezzoLav, (ScostamentoPrezzoRic - (ScostamentoPrezzoMP+ScostamentoPrezzoLav))], 
        'MixValuta' : [BudgetEffettivoRic, BudgetEffettivoMP,BudgetEffettivoLav, (BudgetEffettivoRic - (BudgetEffettivoMP+BudgetEffettivoLav))],
        'ScostamentoValuta' : [ScostamentoValutaRic, 0, 0, (ScostamentoValutaRic - (0+0))],
        'Consuntivo' : [BudgetEffettivoValutaRic, BudgetEffettivoMP, BudgetEffettivoLav, (BudgetEffettivoValutaRic - (BudgetEffettivoMP+BudgetEffettivoLav))],
        'ScostamentoTotale' : [BudgetEffettivoValutaRic-BudgetStandardRic,BudgetEffettivoMP-BudgetStandardMP,BudgetEffettivoLav-BudgetStandardLav, (BudgetEffettivoValutaRic - BudgetStandardRic - (BudgetEffettivoMP-BudgetStandardMP+BudgetEffettivoLav-BudgetStandardLav))]}

In [166]:
pd.DataFrame(data)

,Index,Budget,ScostamentoVolume,MixStandard,ScostamentoMix,MixEffettivo,ScostamentoPrezzo,MixValuta,ScostamentoValuta,Consuntivo,ScostamentoTotale
0,Ricavi,395335.890778,115196.850787,510532.741565,2907.703568,513440.445134,55949.299266,569389.744399,-61546.894857,507842.849542,112506.958764
1,CostiMP,192204.420000,-3058.736402,189145.683598,83377.544336,272523.227934,16510.302066,289033.530000,0.000000,289033.530000,96829.110000
2,CostiLav,192493.776242,57586.739818,250080.516059,31209.399594,281289.915653,77445.140220,358735.055873,0.000000,358735.055873,166241.279631
3,Margine,10637.694536,60668.847371,71306.541908,-111679.240361,-40372.698453,-38006.143020,-78378.841473,-61546.894857,-139925.736331,-150563.430867

come vedremo, i volumi di vendita non coincidono ai volumi di produzione, come negli esercizi fatti a lezione.

Invece, a budget, si vendenono circa 412 prodotti diversi, mentre si lavorano circa 503, dei quali soltanto 73 passano per una fase di montaggio nell'anno in quesitone.

Questo ci porta alla conclusione che ci sono delle rimanenze, e non tutto cio che e prodotto nell'anno e venduto nello stesso anno.

In [167]:
impiegoBudgetNew

,NrArticolo,budgetConsuntivo,Descrizione,NrAreaProduzione,TempoRisorsa,CostoOrario,QuantitydiOutput
0,ART0000018,BUDGET,Controllo qualità,CQ,0.00,12.750000,2.0
1,ART0000018,BUDGET,Fresatura,A30,0.75,51.000000,2.0
2,ART0000018,BUDGET,Tornitura,A20,1.00,68.000000,2.0
3,ART0000041,BUDGET,Controllo qualità,CQ,0.00,12.750000,4.0
4,ART0000041,BUDGET,Fresatura,A30,1.25,51.000000,4.0
...,...,...,...,...,...,...,...
1222,ART0005136,BUDGET,Foratura/Maschiatura,A32,3.00,42.500000,0.0
1223,ART0005136,BUDGET,Fresatura,A30,21.33,47.600000,4.0
1224,ART0005136,BUDGET,Montaggio,A40,8.25,42.500000,0.0
1225,ART0005136,BUDGET,Taglio spezzoni,A20,4.50,68.000000,29.0
1226,ART0005136,BUDGET,Tornitura,A20,53.75,65.166667,51.0

In [168]:
sqldf('select NrArticolo, QuantitydiOutput from impiegoBudgetNew group by NrArticolo,QuantitydiOutput order by NrArticolo')

     NrArticolo  QuantitydiOutput
0    ART0000018               2.0
1    ART0000041               4.0
2    ART0000042               4.0
3    ART0000043               2.0
4    ART0000115               3.0
..          ...               ...
560  ART0005136               4.0
561  ART0005136              29.0
562  ART0005136              32.0
563  ART0005136              50.0
564  ART0005136              51.0

[565 rows x 2 columns]

In [169]:
sqldf('select NrArticolo,Quantity from venditeBudget group by NrArticolo,Quantity order by NrArticolo')

     NrArticolo  Quantity
0    ART0000018         2
1    ART0000041         4
2    ART0000042         4
3    ART0000043         2
4    ART0000115         1
..          ...       ...
585  ART0005136        30
586  ART0005136        32
587  ART0005136        42
588  ART0005136        50
589  ART0005136        64

[590 rows x 2 columns]

In [170]:
sqldf('select NrArticolo,sum(Quantity) as quantita from venditeBudget group by NrArticolo order by NrArticolo')

     NrArticolo  quantita
0    ART0000018         2
1    ART0000041         4
2    ART0000042         4
3    ART0000043         2
4    ART0000115        12
..          ...       ...
408  ART0005109         4
409  ART0005110         2
410  ART0005111         2
411  ART0005112         2
412  ART0005136       630

[413 rows x 2 columns]

In [171]:
sqldf("SELECT DISTINCT NrArticolo FROM dfImpiegoRisorse WHERE (budgetConsuntivo = 'BUDGET' or budgetConsuntivo = 'Budget')")

     NrArticolo
0    ART0000018
1    ART0000041
2    ART0000042
3    ART0000043
4    ART0000115
..          ...
499  ART0005109
500  ART0005110
501  ART0005111
502  ART0005112
503  ART0005136

[504 rows x 1 columns]

In [172]:
sqldf("SELECT DISTINCT NrArticolo,QuantitydiOutput FROM dfImpiegoRisorse WHERE (budgetConsuntivo = 'BUDGET' or budgetConsuntivo = 'Budget') and Descrizione = 'Montaggio'")

    NrArticolo  QuantitydiOutput
0   ART0000748              50.0
1   ART0000748              10.0
2   ART0000748              30.0
3   ART0000752               1.0
4   ART0000752               6.0
..         ...               ...
69  ART0004099               1.0
70  ART0004104               4.0
71  ART0004146              31.0
72  ART0004146               0.0
73  ART0005136               0.0

[74 rows x 2 columns]

In [173]:
pd.merge(
    sqldf('select NrArticolo,sum(Quantity) as quantita from venditeBudget group by NrArticolo order by NrArticolo'),
    sqldf("SELECT DISTINCT NrArticolo,QuantitydiOutput FROM dfImpiegoRisorse WHERE (budgetConsuntivo = 'BUDGET' or budgetConsuntivo = 'Budget') and Descrizione = 'Montaggio'"), 
    on='NrArticolo', how='outer')

     NrArticolo  quantita  QuantitydiOutput
0    ART0000018         2               NaN
1    ART0000041         4               NaN
2    ART0000042         4               NaN
3    ART0000043         2               NaN
4    ART0000115        12               NaN
..          ...       ...               ...
439  ART0005109         4               NaN
440  ART0005110         2               NaN
441  ART0005111         2               NaN
442  ART0005112         2               NaN
443  ART0005136       630               0.0

[444 rows x 3 columns]

In [174]:
venditeConsuntivo.to_excel('venditeConsuntivo.xlsx')

# By Criterion

## By client

In [175]:
def by_client(dfVendite, client):
        dfVendite.rename(columns = {'budget/cons':'budget'}, inplace = True)
        venditeConsuntivo = sqldf("SELECT DISTINCT * FROM dfVendite WHERE budget = 'CONSUNTIVO' or budget = 'Consuntivo'")
        venditeBudget = sqldf("SELECT DISTINCT * FROM dfVendite WHERE budget = 'BUDGET' or budget = 'Budget'")

        venditeConsuntivo = sqldf('''SELECT DISTINCT v.NrMovimento, v.budget, v.NrArticolo, v.Quantity, v.ImportoVenditaValutaLocaleTOTALEVENDITA,k.TassoCambioMedio,v.ImportoVenditaValutaLocaleTOTALEVENDITA/k.TassoCambioMedio as TotaleEuro, v.NrOrigine, c.CodCondizioniPagam, c.FattCumulative, c.Valuta
        FROM venditeConsuntivo as v join dfClienti as c on v.NrOrigine = c.Nr join dfCambio as k on c.Valuta = k.CodiceValuta
        where k.Anno = 'Consuntivo' or k.Anno = 'CONSUNTIVO'
        ''')

        venditeBudget = sqldf('''SELECT DISTINCT v.NrMovimento, v.budget, v.NrArticolo, v.Quantity, v.ImportoVenditaValutaLocaleTOTALEVENDITA,k.TassoCambioMedio,v.ImportoVenditaValutaLocaleTOTALEVENDITA/k.TassoCambioMedio as TotaleEuro, v.NrOrigine, c.CodCondizioniPagam, c.FattCumulative, c.Valuta
        FROM venditeBudget as v join dfClienti as c on v.NrOrigine = c.Nr join dfCambio as k on c.Valuta = k.CodiceValuta
        where k.Anno = 'Budget' or k.Anno = 'BUDGET'
        ''')

        venditeConsuntivo = sqldf('select * from venditeConsuntivo where NrOrigine = "'+client+'"')

        venditeBudget = sqldf('select * from venditeBudget where NrOrigine = "'+client+'"')

        venditeConsuntivoArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity,  sum(ImportoVenditaValutaLocaleTOTALEVENDITA) as TotaleLocale, Valuta, TassoCambioMedio
                from venditeConsuntivo
                group by NrArticolo, Valuta, TassoCambioMedio''')
        venditeBudgetArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity, sum(ImportoVenditaValutaLocaleTOTALEVENDITA) as TotaleLocale, Valuta, TassoCambioMedio
                from venditeBudget
                group by NrArticolo, Valuta, TassoCambioMedio ''')

        venditeConsuntivoS = sqldf('''select NrArticolo, (Quantity*100000000000/9329) as Mix, 9329 as VolumeTotale, TotaleLocale/Quantity as PrezzoUnitario, Valuta, TassoCambioMedio, (TotaleLocale/Quantity)/TassoCambioMedio as PrezzoUnitarioEuro
                from venditeConsuntivoArt''')
        venditeBudgetS = sqldf('''select NrArticolo, (Quantity*100000000000/7224) as Mix, 7224 as VolumeTotale, TotaleLocale/Quantity as PrezzoUnitario, Valuta, TassoCambioMedio, (TotaleLocale/Quantity)/TassoCambioMedio as PrezzoUnitarioEuro
                from venditeBudgetArt''')

        venditeS1 = pd.merge(venditeConsuntivoS, venditeBudgetS, on = ['NrArticolo', 'Valuta'], how = 'outer')
        venditeS1.fillna(0, inplace = True)
        venditeS1


        BudgetStandardRic = sqldf('select sum(Mix_y*VolumeTotale_y*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
        MixStandardRic = sqldf('select sum(Mix_y*VolumeTotale_x*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
        MixEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
        BudgetEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
        BudgetEffettivoValutaRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x/TassoCambioMedio_x)/100000000000 from venditeS1 ').iloc[0][0]

        if(BudgetStandardRic is None):
           BudgetStandardRic = 0

        if(BudgetEffettivoValutaRic is None):
          BudgetEffettivoValutaRic = 0

        ScostamentoVolumeRic = MixStandardRic-BudgetStandardRic
        ScostamentoMixRic = MixEffettivoRic-MixStandardRic
        ScostamentoPrezzoRic = BudgetEffettivoRic-MixEffettivoRic
        ScostamentoValutaRic = BudgetEffettivoValutaRic-BudgetEffettivoRic

        dicResult = {
        'BudgetStandardRic':BudgetStandardRic,
        'MixStandardRic':MixStandardRic,
        'MixEffettivoRic':MixEffettivoRic,
        'BudgetEffettivoRic':BudgetEffettivoRic,
        'BudgetEffettivoValutaRic':BudgetEffettivoValutaRic,
        'ScostamentoVolumeRic':ScostamentoVolumeRic,
        'ScostamentoMixRic':ScostamentoMixRic,
        'ScostamentoPrezzoRic':ScostamentoPrezzoRic,
        'ScostamentoValutaRic':ScostamentoValutaRic,
        'ScostamentoTotaleRic' : ScostamentoVolumeRic+ScostamentoMixRic+ScostamentoPrezzoRic+ScostamentoValutaRic
        }

        return dicResult

In [176]:
e = by_client(dfVendite, 'C00471')
e

{'BudgetStandardRic': 14292.79945018925,
 'MixStandardRic': 18457.57559119816,
 'MixEffettivoRic': 37328.980168508795,
 'BudgetEffettivoRic': 39465.894976324234,
 'BudgetEffettivoValutaRic': 34687.734423866736,
 'ScostamentoVolumeRic': 4164.7761410089115,
 'ScostamentoMixRic': 18871.404577310634,
 'ScostamentoPrezzoRic': 2136.9148078154394,
 'ScostamentoValutaRic': -4778.160552457499,
 'ScostamentoTotaleRic': 20394.934973677486}

In [177]:
def by_client(dfVendite,dfConsumi,impiegoConsuntivo1, impiegoBudget1, client):

       dfVendite.rename(columns = {'budget/cons':'budget'}, inplace = True)
       venditeConsuntivo = sqldf("SELECT DISTINCT * FROM dfVendite WHERE budget = 'CONSUNTIVO' or budget = 'Consuntivo'")
       venditeBudget = sqldf("SELECT DISTINCT * FROM dfVendite WHERE budget = 'BUDGET' or budget = 'Budget'")

       venditeConsuntivo = sqldf('''SELECT DISTINCT v.NrMovimento, v.budget, v.NrArticolo, v.Quantity, v.ImportoVenditaValutaLocaleTOTALEVENDITA,k.TassoCambioMedio,v.ImportoVenditaValutaLocaleTOTALEVENDITA/k.TassoCambioMedio as TotaleEuro, v.NrOrigine, c.CodCondizioniPagam, c.FattCumulative, c.Valuta
       FROM venditeConsuntivo as v join dfClienti as c on v.NrOrigine = c.Nr join dfCambio as k on c.Valuta = k.CodiceValuta
       where k.Anno = 'Consuntivo' or k.Anno = 'CONSUNTIVO'
       ''')

       venditeBudget = sqldf('''SELECT DISTINCT v.NrMovimento, v.budget, v.NrArticolo, v.Quantity, v.ImportoVenditaValutaLocaleTOTALEVENDITA,k.TassoCambioMedio,v.ImportoVenditaValutaLocaleTOTALEVENDITA/k.TassoCambioMedio as TotaleEuro, v.NrOrigine, c.CodCondizioniPagam, c.FattCumulative, c.Valuta
       FROM venditeBudget as v join dfClienti as c on v.NrOrigine = c.Nr join dfCambio as k on c.Valuta = k.CodiceValuta
       where k.Anno = 'Budget' or k.Anno = 'BUDGET'
       ''')

       venditeConsuntivo = sqldf('select * from venditeConsuntivo where NrOrigine = "'+client+'"')

       venditeBudget = sqldf('select * from venditeBudget where NrOrigine = "'+client+'"')

       venditeConsuntivoArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity,  sum(ImportoVenditaValutaLocaleTOTALEVENDITA) as TotaleLocale, Valuta, TassoCambioMedio
       from venditeConsuntivo
       group by NrArticolo, Valuta, TassoCambioMedio''')
       venditeBudgetArt = sqldf('''select NrArticolo, sum(Quantity) as Quantity, sum(ImportoVenditaValutaLocaleTOTALEVENDITA) as TotaleLocale, Valuta, TassoCambioMedio
       from venditeBudget
       group by NrArticolo, Valuta, TassoCambioMedio ''')

       venditeConsuntivoS = sqldf('''select NrArticolo, (Quantity*100000000000/9329) as Mix, 9329 as VolumeTotale, TotaleLocale/Quantity as PrezzoUnitario, Valuta, TassoCambioMedio, (TotaleLocale/Quantity)/TassoCambioMedio as PrezzoUnitarioEuro
       from venditeConsuntivoArt''')
       venditeBudgetS = sqldf('''select NrArticolo, (Quantity*100000000000/7224) as Mix, 7224 as VolumeTotale, TotaleLocale/Quantity as PrezzoUnitario, Valuta, TassoCambioMedio, (TotaleLocale/Quantity)/TassoCambioMedio as PrezzoUnitarioEuro
       from venditeBudgetArt''')

       venditeS1 = pd.merge(venditeConsuntivoS, venditeBudgetS, on = ['NrArticolo', 'Valuta'], how = 'outer')
       venditeS1.fillna(0, inplace = True)
       venditeS1


       BudgetStandardRic = sqldf('select sum(Mix_y*VolumeTotale_y*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
       MixStandardRic = sqldf('select sum(Mix_y*VolumeTotale_x*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
       MixEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_y/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
       BudgetEffettivoRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x/TassoCambioMedio_y)/100000000000 from venditeS1 ').iloc[0][0]
       BudgetEffettivoValutaRic = sqldf('select sum(Mix_x*VolumeTotale_x*PrezzoUnitario_x/TassoCambioMedio_x)/100000000000 from venditeS1 ').iloc[0][0]

       if(BudgetStandardRic is None):
         BudgetStandardRic = 0

       if(MixStandardRic is None):
               MixStandardRic = 0
       
       if(MixEffettivoRic is None):
               MixEffettivoRic = 0
       
       if(BudgetEffettivoRic is None):
               BudgetEffettivoRic = 0

       if(BudgetEffettivoValutaRic is None):
         BudgetEffettivoValutaRic = 0

       ScostamentoVolumeRic = MixStandardRic-BudgetStandardRic
       ScostamentoMixRic = MixEffettivoRic-MixStandardRic
       ScostamentoPrezzoRic = BudgetEffettivoRic-MixEffettivoRic
       ScostamentoValutaRic = BudgetEffettivoValutaRic-BudgetEffettivoRic

       

       # materia prima

       articoli = sqldf('select distinct NrArticolo from venditeS1')

       dfConsumi.rename(columns = {'Budget/cons':'budget'}, inplace = True)
       consumiConsuntivo = sqldf("SELECT DISTINCT * FROM dfConsumi WHERE budget = 'CONSUNTIVO' and NrArticolo in (select * from articoli)")
       consumiBudget = sqldf("SELECT DISTINCT * FROM dfConsumi WHERE budget = 'BUDGET' and NrArticolo in (select * from articoli)") 

       consumiConsuntivoUnit = sqldf('''select distinct NrMovimento, CodiceMP, NrArticolo, QuantityMPImpiegata, ImportoCostoTOTALE/QuantityMPImpiegata as CostoUnitario, ImportoCostoTOTALE 
       from consumiConsuntivo
       order by CodiceMP''')
       consumiBudgetUnit = sqldf('''select distinct NrMovimento, CodiceMP, NrArticolo, QuantityMPImpiegata, ImportoCostoTOTALE/QuantityMPImpiegata as CostoUnitario, ImportoCostoTOTALE 
       from consumiBudget
       order by CodiceMP''')

       consumiConsuntivoUnitByMP = sqldf('''select CodiceMP, NrArticolo,938999.16 as Volume, sum(QuantityMPImpiegata) as QuantityMPImpiegata,sum(ImportoCostoTOTALE)/sum(QuantityMPImpiegata) as CostoUnitario , sum(ImportoCostoTOTALE) as ImportoCostoTOTALE
       from consumiConsuntivoUnit      
       group by CodiceMP, NrArticolo''')
       consumiBudgetUnitByMP = sqldf('''select CodiceMP, NrArticolo,550834.0 as Volume, sum(QuantityMPImpiegata) as QuantityMPImpiegata,sum(ImportoCostoTOTALE)/sum(QuantityMPImpiegata) as CostoUnitario , sum(ImportoCostoTOTALE) as ImportoCostoTOTALE
       from consumiBudgetUnit      
       group by CodiceMP, NrArticolo''')

       conVol = sqldf('select CodiceMP, sum(QuantityMPImpiegata) as VolumeByMP from consumiConsuntivoUnitByMP group by CodiceMP')
       buVol = sqldf('select CodiceMP, sum(QuantityMPImpiegata) as VolumeByMP from consumiBudgetUnitByMP group by CodiceMP')

       consumiConsuntivoUnitByMP = sqldf('''select CodiceMP, NrArticolo, VolumeByMP, (QuantityMPImpiegata/VolumeByMP) as Impiego, CostoUnitario, ImportoCostoTOTALE
       from consumiConsuntivoUnitByMP natural join conVol ''')
       consumiBudgetUnitByMP = sqldf('''select CodiceMP, NrArticolo, VolumeByMP, (QuantityMPImpiegata/VolumeByMP) as Impiego, CostoUnitario, ImportoCostoTOTALE
       from consumiBudgetUnitByMP natural join buVol''')

       ConsumiUnit = pd.merge(consumiConsuntivoUnitByMP,consumiBudgetUnitByMP, on = ['CodiceMP','NrArticolo'], how = 'outer')

       BudgetEffettivoMP = sqldf('select sum(VolumeByMP_x*Impiego_x*CostoUnitario_x) from ConsumiUnit').iloc[0][0]
       ImpiegoEffettivoMP = sqldf('select sum(VolumeByMP_x*Impiego_x*CostoUnitario_y) from ConsumiUnit').iloc[0][0]
       ImpiegoStandardMP = sqldf('select sum(VolumeByMP_x*Impiego_y*CostoUnitario_y) from ConsumiUnit').iloc[0][0]
       BudgetStandardMP = sqldf('select sum(VolumeByMP_y*Impiego_y*CostoUnitario_y) from ConsumiUnit').iloc[0][0]
       ScostamentoVolumeMP =  ImpiegoStandardMP - BudgetStandardMP
       ScostamentoImpiegoMP = ImpiegoEffettivoMP-ImpiegoStandardMP
       ScostamentoPrezzoMP = BudgetEffettivoMP-ImpiegoEffettivoMP 

       # lavorazioni

       impiegoConsuntivoNew = sqldf(''' select NrArticolo, budgetConsuntivo, NrOrdineProduzione, Descrizione, NrAreaProduzione, Risorsa, TempoRisorsa, TempoRisorsa/QuantitydiOutput as ImpiegoUnitario, CostoOrario ,QuantitydiOutput
       from impiegoConsuntivo1
       where NrArticolo in (select * from articoli)''')
       impiegoConsuntivoNew.drop(['NrOrdineProduzione'], axis=1, inplace=True)

       impiegoConsuntivoNew = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, sum(TempoRisorsa) as TempoRisorsa, avg(CostoOrario) as CostoOrario, sum(QuantitydiOutput) as QuantitydiOutput
       from impiegoConsuntivoNew
       group by NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione
       ''')

       vol = sqldf('select NrArticolo, sum(QuantitydiOutput) as Volume from impiegoConsuntivoNew group by NrArticolo')

       impiegoConsuntivoNew = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, TempoRisorsa, (TempoRisorsa/Volume) as ImpiegoUnitario, CostoOrario, Volume ,QuantitydiOutput
       from impiegoConsuntivoNew natural join vol
       ''')

       impiegoBudgetNew = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, sum(TempoRisorsa) as TempoRisorsa, avg(CostoOrario) as CostoOrario, sum(QuantitydiOutput) as QuantitydiOutput
       from impiegoBudget1
       where NrArticolo in (select * from articoli)
       group by NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione
       ''')
       vol = sqldf('select NrArticolo, sum(QuantitydiOutput) as Volume from impiegoBudgetNew group by NrArticolo')

       impiegoBudgetNew = sqldf(''' select NrArticolo, budgetConsuntivo, Descrizione, NrAreaProduzione, TempoRisorsa, (TempoRisorsa/Volume) as ImpiegoUnitario, CostoOrario, Volume ,QuantitydiOutput
       from impiegoBudgetNew natural join vol
       ''')

       impiegoConsuntivoNew.drop(['budgetConsuntivo'], axis=1, inplace=True)
       impiegoBudgetNew.drop(['budgetConsuntivo'], axis=1, inplace=True)
       x = pd.merge(impiegoConsuntivoNew, impiegoBudgetNew, on=['NrArticolo', 'Descrizione', 'NrAreaProduzione'], how='outer')

       #Budget Standard
       BudgetStandardLav = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_y	) from x').iloc[0][0]
       # Impiego Standard (volume a consuntivo)
       ImpiegoStandardLav = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_x	) from x').iloc[0][0]
       # Impiego Effettivo (volume e impiego a consuntivo)
       ImpiegoEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_y*QuantitydiOutput_x	) from x').iloc[0][0]
       # Budget Effettivo (tutto a consuntivo)
       BudgetEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x	) from x').iloc[0][0]

       ScostamentoVolumeLav = ImpiegoStandardLav-b
       ScostamentoImpiegoLav = ImpiegoEffettivoLav-ImpiegoStandardLav
       ScostamentoPrezzoLav = BudgetEffettivoLav-ImpiegoEffettivoLav

       data = {client: ['Ricavi', 'CostiMP', 'CostiLav', 'Margine'], 
       'Budget' : [BudgetStandardRic, BudgetStandardMP,BudgetStandardLav, (BudgetStandardRic - (BudgetStandardMP+BudgetStandardLav))],
       'ScostamentoVolume' : [ScostamentoVolumeRic,ScostamentoVolumeMP,ScostamentoVolumeLav, (ScostamentoVolumeRic - (ScostamentoVolumeMP+ScostamentoVolumeLav))], 
       'MixStandard' : [MixStandardRic, ImpiegoStandardMP,ImpiegoStandardLav, (MixStandardRic - (ImpiegoStandardMP+ImpiegoStandardLav))],
       'ScostamentoMix' : [ScostamentoMixRic,ScostamentoImpiegoMP,ScostamentoImpiegoLav, (ScostamentoMixRic - (ScostamentoImpiegoMP+ScostamentoImpiegoLav))],
       'MixEffettivo' : [MixEffettivoRic, ImpiegoEffettivoMP,ImpiegoEffettivoLav, (MixEffettivoRic - (ImpiegoEffettivoMP+ImpiegoEffettivoLav))],
       'ScostamentoPrezzo' : [ScostamentoPrezzoRic,ScostamentoPrezzoMP,ScostamentoPrezzoLav, (ScostamentoPrezzoRic - (ScostamentoPrezzoMP+ScostamentoPrezzoLav))], 
       'MixValuta' : [BudgetEffettivoRic, BudgetEffettivoMP,BudgetEffettivoLav, (BudgetEffettivoRic - (BudgetEffettivoMP+BudgetEffettivoLav))],
       'ScostamentoValuta' : [ScostamentoValutaRic, 0, 0, (ScostamentoValutaRic - (0+0))],
       'Consuntivo' : [BudgetEffettivoValutaRic, BudgetEffettivoMP, BudgetEffettivoLav, (BudgetEffettivoValutaRic - (BudgetEffettivoMP+BudgetEffettivoLav))],
       'ScostamentoTotale' : [BudgetEffettivoValutaRic-BudgetStandardRic,BudgetEffettivoMP-BudgetStandardMP,BudgetEffettivoLav-BudgetStandardLav, (BudgetEffettivoValutaRic - BudgetStandardRic - (BudgetEffettivoMP-BudgetStandardMP+BudgetEffettivoLav-BudgetStandardLav))]}

       data = pd.DataFrame(data)

       return data

In [88]:
clients = sqldf('select distinct Nr from dfClienti')
scos = []
count = 0

for client in clients.values:
   theclient = client[0]
   if (sqldf('select * from dfVendite where NrOrigine = "'+theclient+'"').empty):
      continue
   print(theclient)
   scos.append(by_client(dfVendite,dfConsumi,impiegoConsuntivo1, impiegoBudget1, theclient))
   count += 1

C00001
C00003
C00004
C00015
C00017
C00018
C00020
C00026
C00084
C00094
C00117
C00127
C00140
C00158
C00236
C00297
C00344
C00353
C00454
C00455
C00456
C00458
C00461
C00465
C00471
C00473
C00474
C00478
C00479
C00483
C00487
C00489
C00492
C00493
C00498
C00499
C00504

In [89]:
def Func(x):
  return x.iloc[3,10]

scos.sort(key=Func)

In [90]:
scos[0]

,C00140,Budget,ScostamentoVolume,MixStandard,ScostamentoMix,MixEffettivo,ScostamentoPrezzo,MixValuta,ScostamentoValuta,Consuntivo,ScostamentoTotale
0,Ricavi,339345.250517,98881.748663,438226.999179,-31816.279916,406410.719263,50383.994864,456794.714128,-55304.421322,401490.292806,62145.042289
1,CostiMP,148088.440000,74185.889444,222274.329444,-531.712890,221742.616554,2248.293446,223990.910000,0.000000,223990.910000,75902.470000
2,CostiLav,29394.642724,-146280.032028,46213.744214,-4492.997472,41720.746742,7645.537867,49366.284609,0.000000,49366.284609,19971.641884
3,Margine,161862.167793,170975.891246,169738.925522,-26791.569554,142947.355967,40490.163552,183437.519519,-55304.421322,128133.098197,-33729.069596

## By NrArticolo

In [208]:
def by_articolo(mergeImpiego, articolo):
    lavorazioniSingoloProdotto = sqldf('select * from x where NrArticolo = "'+articolo+'"')
    c = sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x) from lavorazioniSingoloProdotto').iloc[0][0]
    b = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_y) from lavorazioniSingoloProdotto').iloc[0][0]

    #Budget Standard
    BudgetStandardLav = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_y) from lavorazioniSingoloProdotto').iloc[0][0]
    # Impiego Standard (volume a consuntivo)
    ImpiegoStandardLav = sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_x) from lavorazioniSingoloProdotto').iloc[0][0]
    # Impiego Effettivo (volume e impiego a consuntivo)
    ImpiegoEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_y*QuantitydiOutput_x) from lavorazioniSingoloProdotto').iloc[0][0]
    # Budget Effettivo (tutto a consuntivo)
    BudgetEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x) from lavorazioniSingoloProdotto').iloc[0][0]

    if(BudgetStandardLav is None):
                BudgetStandardLav = 0

    if(ImpiegoStandardLav is None):
                ImpiegoStandardLav = 0

    if(ImpiegoEffettivoLav is None):
                ImpiegoEffettivoLav = 0

    if(BudgetEffettivoLav is None):
                BudgetEffettivoLav = 0

    #Scostamenti
    ScostamentoVolumeLav = ImpiegoStandardLav-BudgetStandardLav
    ScostamentoImpiegoLav = ImpiegoEffettivoLav-ImpiegoStandardLav
    ScostamentoPrezzoLav = BudgetEffettivoLav-ImpiegoEffettivoLav

    data = {articolo: ['CostiLav'], 
            'Budget' : [BudgetStandardLav],
            'ScostamentoVolume' : [ScostamentoVolumeLav,], 
            'MixStandard' : [ImpiegoStandardLav],
            'ScostamentoMix' : [ScostamentoImpiegoLav],
            'MixEffettivo' : [ImpiegoEffettivoLav],
            'ScostamentoPrezzo' : [ScostamentoPrezzoLav], 
            'MixValuta' : [BudgetEffettivoLav],
            'ScostamentoValuta' : [0],
            'Consuntivo' : [BudgetEffettivoLav],
            'ScostamentoTotale' : [BudgetEffettivoLav-BudgetStandardLav]}

    return pd.DataFrame(data)

In [207]:
lavorazioniSingoloProdotto = sqldf('select * from x where NrArticolo = "'+'ART0004084'+'"')
#Budget Standard
sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_y) from lavorazioniSingoloProdotto')
sqldf('select sum(ImpiegoUnitario_y*CostoOrario_y*QuantitydiOutput_x) from lavorazioniSingoloProdotto')
sqldf('select sum(ImpiegoUnitario_x*CostoOrario_y*QuantitydiOutput_x) from lavorazioniSingoloProdotto')
sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x) from lavorazioniSingoloProdotto')

   sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x)
0                                               75.0

In [ ]:
# Impiego Standard (volume a consuntivo)

# Impiego Effettivo (volume e impiego a consuntivo)
ImpiegoEffettivoLav=.iloc[0][0]
# Budget Effettivo (tutto a consuntivo)
BudgetEffettivoLav=sqldf('select sum(ImpiegoUnitario_x*CostoOrario_x*QuantitydiOutput_x) from lavorazioniSingoloProdotto').iloc[0][0]

In [209]:
by_articolo(x,'ART0004084')

,ART0004084,Budget,ScostamentoVolume,MixStandard,ScostamentoMix,MixEffettivo,ScostamentoPrezzo,MixValuta,ScostamentoValuta,Consuntivo,ScostamentoTotale
0,CostiLav,0,0,0,63.75,63.75,11.25,75.0,0,75.0,75.0

In [210]:
articoli = sqldf('select distinct NrArticolo from dfImpiegoRisorse')
scos = []

for articolo in articoli.values:
   theArticolo = articolo[0]
   if (False):
      continue
   print(theArticolo)
   scos.append(by_articolo(x, theArticolo))

ART0000018
ART0000041
ART0000042
ART0000043
ART0000115
ART0000116
ART0000119
ART0000121
ART0000125
ART0000128
ART0000129
ART0000131
ART0000151
ART0000152
ART0000157
ART0000223
ART0000226
ART0000227
ART0000228
ART0000229
ART0000308
ART0000312
ART0000313
ART0000320
ART0000323
ART0000324
ART0000325
ART0000456
ART0000555
ART0000625
ART0000627
ART0000628
ART0000630
ART0000635
ART0000638
ART0000639
ART0000641
ART0000642
ART0000643
ART0000644
ART0000645
ART0000690
ART0000697
ART0000748
ART0000749
ART0000752
ART0000753
ART0000756
ART0000757
ART0000758
ART0000762
ART0000765
ART0000769
ART0000772
ART0000778
ART0000779
ART0000780
ART0000782
ART0000783
ART0000784
ART0000786
ART0000788
ART0000790
ART0000795
ART0000796
ART0000797
ART0000804
ART0000805
ART0000811
ART0000812
ART0000814
ART0000825
ART0000826
ART0000830
ART0000841
ART0000843
ART0000845
ART0000847
ART0000848
ART0000849
ART0000850
ART0000851
ART0000853
ART0000877
ART0000878
ART0000879
ART0000880
ART0000881
ART0000882
ART0000883
ART0000885
ART0000887
ART0000888
ART0000889
ART0000890
ART0000891
ART0000893
ART0001017
ART0001018
ART0001046
ART0001047
ART0001095
ART0001099
ART0001100
ART0001102
ART0001104
ART0001110
ART0001113
ART0001117
ART0001129
ART0001149
ART0001154
ART0001162
ART0001164
ART0001170
ART0001174
ART0001180
ART0001185
ART0001188
ART0001190
ART0001202
ART0001203
ART0001208
ART0001214
ART0001215
ART0001218
ART0001219
ART0001228
ART0001238
ART0001244
ART0001249
ART0001252
ART0001253
ART0001261
ART0001263
ART0001264
ART0001265
ART0001266
ART0001267
ART0001272
ART0001276
ART0001277
ART0001290
ART0001294
ART0001391
ART0001409
ART0001422
ART0001427
ART0001429
ART0001433
ART0001441
ART0001492
ART0001493
ART0001497
ART0001500
ART0001514
ART0001515
ART0001520
ART0001534
ART0001535
ART0001566
ART0001575
ART0001587
ART0001588
ART0001590
ART0001593
ART0001605
ART0001606
ART0001609
ART0001610
ART0001612
ART0001615
ART0001628
ART0001636
ART0001637
ART0001653
ART0001659
ART0001669
ART0001670
ART0001731
ART0001733
ART0001739
ART0001740
ART0001741
ART0001743
ART0001745
ART0001759
ART0001761
ART0001762
ART0001765
ART0001766
ART0001767
ART0001768
ART0001770
ART0001772
ART0001773
ART0001775
ART0001776
ART0001777
ART0001778
ART0001779
ART0001783
ART0001785
ART0001786
ART0001788
ART0001789
ART0001794
ART0001799
ART0001804
ART0001807
ART0001811
ART0001813
ART0001817
ART0001821
ART0001825
ART0001829
ART0001830
ART0001832
ART0001837
ART0001840
ART0001841
ART0001866
ART0001868
ART0001869
ART0001872
ART0001873
ART0001874
ART0001877
ART0001880
ART0001882
ART0001884
ART0001885
ART0001886
ART0001889
ART0001890
ART0001891
ART0001895
ART0001897
ART0001898
ART0001900
ART0001908
ART0001913
ART0001917
ART0001920
ART0001921
ART0001923
ART0001926
ART0001931
ART0001935
ART0001939
ART0001940
ART0001942
ART0001945
ART0001946
ART0001947
ART0001950
ART0001951
ART0001981
ART0001989
ART0001993
ART0001994
ART0002010
ART0002012
ART0002015
ART0002017
ART0002018
ART0002019
ART0002026
ART0002027
ART0002028
ART0002029
ART0002041
ART0002042
ART0002048
ART0002070
ART0002079
ART0002102
ART0002107
ART0002109
ART0002112
ART0002123
ART0002132
ART0002133
ART0002139
ART0002140
ART0002141
ART0002142
ART0002144
ART0002145
ART0002148
ART0002152
ART0002172
ART0002173
ART0002191
ART0002195
ART0002210
ART0002214
ART0002224
ART0002228
ART0002238
ART0002240
ART0002249
ART0002262
ART0002263
ART0002267
ART0002271
ART0002273
ART0002274
ART0002284
ART0002299
ART0002306
ART0002360
ART0002366
ART0002370
ART0002385
ART0002411
ART0002416
ART0002423
ART0002424
ART0002444
ART0002450
ART0002451
ART0002452
ART0002455
ART0002456
ART0002464
ART0002476
ART0002488
ART0002490
ART0002494
ART0002498
ART0002502
ART0002504
ART0002508
ART0002511
ART0002513
ART0002517
ART0002530
ART0002531
ART0002551
ART0002552
ART0002554
ART0002555
ART0002556
ART0002580
ART0002581
ART0002586
ART0002598
ART0002608
ART0002614
ART0002615
ART0002617
ART0002619
ART0002628
ART0002706
ART0002707
ART0002712
ART0002718
ART0002719
ART0002739
ART0002740
ART0002747
ART0002753
ART0002755
ART0002793
ART0002829
ART0002836
ART0002859
ART0002860
ART0002866
ART0002867
ART0002882
ART0002886
ART0002895
ART0002896
ART0002897
ART0002909
ART0002918
ART0002919
ART0002938
ART0002949
ART0002958
ART0002959
ART0002961
ART0002962
ART0002963
ART0002968
ART0002969
ART0002978
ART0002988
ART0002989
ART0002990
ART0002996
ART0002997
ART0003099
ART0003101
ART0003105
ART0003132
ART0003135
ART0003160
ART0003164
ART0003167
ART0003169
ART0003189
ART0003195
ART0003197
ART0003202
ART0003263
ART0003268
ART0003269
ART0003275
ART0003277
ART0003309
ART0003310
ART0003578
ART0003580
ART0003609
ART0003610
ART0003612
ART0003613
ART0003642
ART0003704
ART0003780
ART0003782
ART0003785
ART0003824
ART0003844
ART0003935
ART0003940
ART0003982
ART0003984
ART0003989
ART0004014
ART0004015
ART0004084
ART0004099
ART0004104
ART0004146
ART0004149
ART0004152
ART0004169
ART0004175
ART0004202
ART0004357
ART0004362
ART0004363
ART0004373
ART0004374
ART0004375
ART0004384
ART0004385
ART0004386
ART0004392
ART0004397
ART0004403
ART0004410
ART0004420
ART0004440
ART0004656
ART0004659
ART0004660
ART0004671
ART0004675
ART0004689
ART0004697
ART0004711
ART0004717
ART0004718
ART0004724
ART0004725
ART0004726
ART0004727
ART0004737
ART0004836
ART0004880
ART0004885
ART0004886
ART0004889
ART0004898
ART0004901
ART0004902
ART0004904
ART0004919
ART0004924
ART0004941
ART0004942
ART0004944
ART0004946
ART0004947
ART0005011
ART0005026
ART0005028
ART0005029
ART0005030
ART0005034
ART0005035
ART0005036
ART0005037
ART0005091
ART0005109
ART0005110
ART0005111
ART0005112
ART0005136

In [216]:
def Func(x):
  return x.iloc[0,10]

scos.sort(key=Func)
scos

[  ART0001897       Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  4546.231545        -169.028571  4377.202974    -3336.797024

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0    1040.40595          319.60205   1360.008                  0    1360.008

    ScostamentoTotale
 0       -3186.223545  ,
   ART0001785    Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  2503.675                0.0     2503.675         -1671.1

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       832.575             87.425      920.0                  0       920.0

    ScostamentoTotale
 0          -1583.675  ,
   ART0001942       Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1714.172333       -1055.422333       658.75     -375.416667

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0    283.333333         116.666667      400.0                  0       400.0

    ScostamentoTotale
 0       -1314.172333  ,
   ART0001931  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1776.5        -592.166667  1184.333333     -772.083333

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        412.25             100.25      512.5                  0       512.5

    ScostamentoTotale
 0            -1264.0  ,
   ART0001154  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1232.5             -773.5        459.0        -172.125

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       286.875            -16.875      270.0                  0       270.0

    ScostamentoTotale
 0             -962.5  ,
   ART0000762   Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1126.25           -563.125      563.125        -414.375

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        148.75              26.25      175.0                  0       175.0

    ScostamentoTotale
 0            -951.25  ,
   ART0001872     Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1175.1845        -555.392833   619.791667     -381.791667

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         238.0               82.0      320.0                  0       320.0

    ScostamentoTotale
 0          -855.1845  ,
   ART0003940      Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  2781.20493          446.67007     3227.875       -1770.125

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       1457.75             589.75     2047.5                  0      2047.5

    ScostamentoTotale
 0         -733.70493  ,
   ART0000151  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  607.75            -607.75          0.0             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0           0.0                0.0        0.0                  0         0.0

    ScostamentoTotale
 0            -607.75  ,
   ART0001745  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   739.5             -484.5        255.0          -102.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         153.0               -3.0      150.0                  0       150.0

    ScostamentoTotale
 0             -589.5  ,
   ART0001244   Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  941.375            -140.25      801.125         -442.17

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       358.955             52.545      411.5                  0       411.5

    ScostamentoTotale
 0           -529.875  ,
   ART0004146      Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  430.666667        -430.666667          0.0             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0             0                  0          0                  0           0

    ScostamentoTotale
 0        -430.666667  ,
   ART0005028  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   994.5              204.0       1198.5          -663.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         535.5               39.5      575.0                  0       575.0

    ScostamentoTotale
 0             -419.5  ,
   ART0002747  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   408.0             -331.5         76.5           -25.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0          51.0               -1.0       50.0                  0        50.0

    ScostamentoTotale
 0             -358.0  ,
   ART0001265    Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1561.875                0.0     1561.875        -478.125

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       1083.75             166.25     1250.0                  0      1250.0

    ScostamentoTotale
 0           -311.875  ,
   ART0004886  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1589.5                0.0       1589.5          -481.1

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        1108.4              195.6     1304.0                  0      1304.0

    ScostamentoTotale
 0             -285.5  ,
   ART0002997  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   705.5                0.0        705.5          -331.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         374.0               66.0      440.0                  0       440.0

    ScostamentoTotale
 0             -265.5  ,
   ART0002608  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  327.25             -238.0        89.25           -25.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         63.75              -1.25       62.5                  0        62.5

    ScostamentoTotale
 0            -264.75  ,
   ART0002456  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  539.75            -106.25        433.5         -140.25

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        293.25              -5.75      287.5                  0       287.5

    ScostamentoTotale
 0            -252.25  ,
   ART0002938  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   552.5            -276.25       276.25            -8.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        267.75              34.75      302.5                  0       302.5

    ScostamentoTotale
 0             -250.0  ,
   ART0000223   Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  499.375           -406.875         92.5           120.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         212.5               37.5      250.0                  0       250.0

    ScostamentoTotale
 0           -249.375  ,
   ART0002102  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   671.5        -353.730769   317.769231       11.605769

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       329.375            105.625      435.0                  0       435.0

    ScostamentoTotale
 0             -236.5  ,
   ART0002228  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  344.25            -267.75         76.5           63.75

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        140.25              -2.75      137.5                  0       137.5

    ScostamentoTotale
 0            -206.75  ,
   ART0003609  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  522.75        -355.840909   166.909091      123.507576

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0    290.416667          32.083333      322.5                  0       322.5

    ScostamentoTotale
 0            -200.25  ,
   ART0004363  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   285.6        -275.751724     9.848276       92.151724

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         102.0              -12.0       90.0                  0        90.0

    ScostamentoTotale
 0             -195.6  ,
   ART0002581  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  412.25              72.25        484.5          -255.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         229.5               -4.5      225.0                  0       225.0

    ScostamentoTotale
 0            -187.25  ,
   ART0002263  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  284.75            -131.75        153.0           -51.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         102.0               -2.0      100.0                  0       100.0

    ScostamentoTotale
 0            -184.75  ,
   ART0002027  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   314.5                0.0        314.5          -195.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         119.0               11.0      130.0                  0       130.0

    ScostamentoTotale
 0             -184.5  ,
   ART0001628  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   238.0             -190.4         47.6          -7.735

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        39.865             13.735       53.6                  0        53.6

    ScostamentoTotale
 0             -184.4  ,
   ART0003844    Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  392.0625            261.375     653.4375       -447.3125

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0       206.125              3.875      210.0                  0       210.0

    ScostamentoTotale
 0          -182.0625  ,
   ART0004880  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   331.5            -165.75       165.75          -38.25

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         127.5               22.5      150.0                  0       150.0

    ScostamentoTotale
 0             -181.5  ,
   ART0001821  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   510.0             -170.0        340.0           -34.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         306.0               39.0      345.0                  0       345.0

    ScostamentoTotale
 0             -165.0  ,
   ART0000125  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   586.5             -195.5        391.0           29.75

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        420.75               1.75      422.5                  0       422.5

    ScostamentoTotale
 0             -164.0  ,
   ART0000320  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   289.0             -153.0        136.0            -8.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         127.5               -2.5      125.0                  0       125.0

    ScostamentoTotale
 0             -164.0  ,
   ART0001789  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   374.0             -170.0        204.0           -25.5

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         178.5               31.5      210.0                  0       210.0

    ScostamentoTotale
 0             -164.0  ,
   ART0004014  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  905.25                0.0       905.25         -427.38

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        477.87             264.33      742.2                  0       742.2

    ScostamentoTotale
 0            -163.05  ,
   ART0003704  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   552.5            -403.75       148.75           204.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        352.75              39.75      392.5                  0       392.5

    ScostamentoTotale
 0             -160.0  ,
   ART0002012    Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  398.4375          199.21875    597.65625      -335.21875

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0      262.4375           -19.9375      242.5                  0       242.5

    ScostamentoTotale
 0          -155.9375  ,
   ART0003309      Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  198.333333         -45.769231   152.564103      -95.897436

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0     56.666667           3.333333       60.0                  0        60.0

    ScostamentoTotale
 0        -138.333333  ,
   ART0002140  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   272.0              136.0        408.0          -272.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         136.0                4.0      140.0                  0       140.0

    ScostamentoTotale
 0             -132.0  ,
   ART0002959  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  216.75             -153.0        63.75          10.625

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        74.375             13.125       87.5                  0        87.5

    ScostamentoTotale
 0            -129.25  ,
   ART0004152  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   637.5             743.75      1381.25         -947.75

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         433.5               76.5      510.0                  0       510.0

    ScostamentoTotale
 0             -127.5  ,
   ART0002958   Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  201.875            -148.75       53.125          10.625

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         63.75              11.25       75.0                  0        75.0

    ScostamentoTotale
 0           -126.875  ,
   ART0002580    Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  445.1875            890.375    1335.5625    -1063.557825

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0    272.004675          48.003325    320.008                  0     320.008

    ScostamentoTotale
 0          -125.1795  ,
   ART0000812  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  191.25             -127.5        63.75          -7.225

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        56.525              9.975       66.5                  0        66.5

    ScostamentoTotale
 0            -124.75  ,
   ART0004898   Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  184.875        -140.740385    44.134615        8.990385

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        53.125              9.375       62.5                  0        62.5

    ScostamentoTotale
 0           -122.375  ,
   ART0004904  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   119.0             -119.0          0.0             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0           0.0                0.0        0.0                  0         0.0

    ScostamentoTotale
 0             -119.0  ,
   ART0004944  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   119.0             -119.0          0.0             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0           0.0                0.0        0.0                  0         0.0

    ScostamentoTotale
 0             -119.0  ,
   ART0004737   Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  116.875           -116.875          0.0             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0           0.0                0.0        0.0                  0         0.0

    ScostamentoTotale
 0           -116.875  ,
   ART0002271      Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  596.416667         149.104167   745.520833     -348.854167

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0    396.666667          83.333333      480.0                  0       480.0

    ScostamentoTotale
 0        -116.416667  ,
   ART0001788  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  1147.5                0.0       1147.5       -395.2449

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0      752.2551           281.5014  1033.7565                  0   1033.7565

    ScostamentoTotale
 0          -113.7435  ,
   ART0000042  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   433.5                0.0        433.5       -229.4949

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0      204.0051           116.0029    320.008                  0     320.008

    ScostamentoTotale
 0           -113.492  ,
   ART0000826  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   127.5              -85.0         42.5         -28.475

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0        14.025              2.475       16.5                  0        16.5

    ScostamentoTotale
 0             -111.0  ,
   ART0000152  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  395.25                0.0       395.25         -148.75

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         246.5               41.0      287.5                  0       287.5

    ScostamentoTotale
 0            -107.75  ,
   ART0002552  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  386.75        -205.416667   181.333333           48.96

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0    230.293333          49.106667      279.4                  0       279.4

    ScostamentoTotale
 0            -107.35  ,
   ART0001778  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav  140.25             -102.0        38.25             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \
 0         38.25              -0.75       37.5                  0        37.5

    ScostamentoTotale
 0            -102.75  ,
   ART0004901  Budget  ScostamentoVolume  MixStandard  ScostamentoMix  \
 0   CostiLav   102.0             -102.0          0.0             0.0

    MixEffettivo  ScostamentoPrezzo  MixValuta  ScostamentoValuta  Consuntivo  \

# Scratchpad

In [ ]:
y = sqldf('select NrArticolo,count(descrizione) from impiegoBudget1 group by NrArticolo having Descrizione = "Controllo qualità" or Descrizione = "Montaggio"')
y

     NrArticolo  count(descrizione)
0    ART0000018                   3
1    ART0000041                   3
2    ART0000042                   3
3    ART0000121                   1
4    ART0000125                   7
..          ...                 ...
432  ART0005109                   2
433  ART0005110                   1
434  ART0005111                   2
435  ART0005112                   2
436  ART0005136                  60

[437 rows x 2 columns]

In [ ]:
x = sqldf('select NrArticolo,count(descrizione) from impiegoBudget1 group by NrArticolo')
x

     NrArticolo  count(descrizione)
0    ART0000018                   3
1    ART0000041                   3
2    ART0000042                   3
3    ART0000043                   4
4    ART0000115                   2
..          ...                 ...
499  ART0005109                   2
500  ART0005110                   1
501  ART0005111                   2
502  ART0005112                   2
503  ART0005136                  60

[504 rows x 2 columns]

In [ ]:
sqldf ('select NrArticolo from x where NrArticolo not in (select NrArticolo from y)')

    NrArticolo
0   ART0000043
1   ART0000115
2   ART0000116
3   ART0000119
4   ART0000157
..         ...
62  ART0004363
63  ART0004836
64  ART0004886
65  ART0004941
66  ART0005026

[67 rows x 1 columns]